<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Profil_toggle-sidebar (48)</name>
   <tag></tag>
   <elementGuidId>0f54ba90-6d23-4dff-89ef-6e70b8b6f14d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='toggle-sidebar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toggle-sidebar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0fa7a292-3146-46e2-9f9e-cc3527aa80a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggle-sidebar</value>
      <webElementGuid>263dcd7c-ecbd-4283-bec5-8171c17a3223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>c5645ca8-24a2-40a8-bd2f-c120fc8f4943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-widget</name>
      <type>Main</type>
      <value>pushmenu</value>
      <webElementGuid>db3d0aef-0dab-4f25-b31b-000a5001b5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>bf142bc4-fcab-4189-9549-31834293f9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>897c9d12-feb2-4da5-821e-cf0e5b87097a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle-sidebar&quot;)</value>
      <webElementGuid>0c0b3627-7c2d-4299-a1ac-a6a834eb1efd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='toggle-sidebar']</value>
      <webElementGuid>f26de2e4-c2d7-4d8b-8d12-a9df93af65df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>591ea4f7-d8b8-4410-bba5-7d88afa1e2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>2c7d672e-c9a9-4552-b5ab-0420d60a1e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'toggle-sidebar' and @href = '#']</value>
      <webElementGuid>801cb806-a8c1-44f2-9e7b-6c073def0e9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
