<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Profil_toggle-sidebar (38)</name>
   <tag></tag>
   <elementGuidId>b3ac09c1-a7af-4821-9edb-6c9384a84d59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='toggle-sidebar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toggle-sidebar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9784fd8f-6c80-4cbf-97fa-30451e736585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggle-sidebar</value>
      <webElementGuid>fe5ab6ad-9709-442f-8653-2c786061850f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>5c5b38d5-c6e2-4c1c-9099-2bb212c34132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-widget</name>
      <type>Main</type>
      <value>pushmenu</value>
      <webElementGuid>a46a2e64-e763-4460-8174-95fa38824745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>dfaf6180-8db3-46cc-ac4f-237b44af4985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a68f34a-bc21-4ea7-b694-0d4f95a9889a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle-sidebar&quot;)</value>
      <webElementGuid>d7ae1f1c-8023-4f8e-90e2-30110de143a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='toggle-sidebar']</value>
      <webElementGuid>84c99463-73a1-4fe2-98fe-76249dddcfe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>6195c2e4-9747-40a9-ac8d-764828285642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>1bf02e08-bc2d-462f-916b-a45dccbaea70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'toggle-sidebar' and @href = '#']</value>
      <webElementGuid>67ef9188-a6a5-45cc-938a-e51bd1498d9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
