<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kategori</name>
   <tag></tag>
   <elementGuidId>b9c5a78e-ffec-48fc-915c-3b145e46e357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='data']/table/thead/tr/th[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2b7ac6fe-7d04-48d1-a914-4338d11737ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/backend/web/index.php?r=lembaga%2Findex&amp;sort=kategori</value>
      <webElementGuid>2718b594-2527-4eb0-8f70-5da4c4e5d022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sort</name>
      <type>Main</type>
      <value>kategori</value>
      <webElementGuid>9ea0617d-3d0a-4413-bdd6-f05af87f182e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori</value>
      <webElementGuid>146571d4-5e8c-41e1-acdf-14a06924a47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data&quot;)/table[@class=&quot;table table-striped table-hover&quot;]/thead[1]/tr[1]/th[3]/a[1]</value>
      <webElementGuid>f1928e7e-e963-446e-bb16-7205a241818c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data']/table/thead/tr/th[3]/a</value>
      <webElementGuid>e45e06cf-318b-47ed-bb6a-bb321489d65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kategori')]</value>
      <webElementGuid>ef282cbb-70c8-41c5-99ea-b28aaab1f48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Lembaga'])[1]/following::a[1]</value>
      <webElementGuid>4c3858f5-e450-4108-b17e-f03994cc9f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[1]/following::a[2]</value>
      <webElementGuid>7d58d0c1-f2f4-459b-9b6a-7bf2051ae495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[2]/preceding::a[1]</value>
      <webElementGuid>2bb2f4ef-c78f-48c3-a715-f6865161b42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota'])[2]/preceding::a[2]</value>
      <webElementGuid>b4d5b737-0be5-475d-aee8-7fc9f624af3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/backend/web/index.php?r=lembaga%2Findex&amp;sort=kategori')]</value>
      <webElementGuid>920c0c97-c964-4b67-8c07-35563f338a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/a</value>
      <webElementGuid>94836b6c-6aef-498f-9c24-32722d59b564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/backend/web/index.php?r=lembaga%2Findex&amp;sort=kategori' and (text() = 'Kategori' or . = 'Kategori')]</value>
      <webElementGuid>6355ff91-a5cf-446d-9399-522fd647e373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
