<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tampilkan Semua</name>
   <tag></tag>
   <elementGuidId>b181157d-f01b-45a1-b2f1-27a5d0ef4e90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='w0']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c7de64a6-d401-4e21-b7d9-ab063f93bd0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>3a5317ee-2d3e-4d14-93de-d3b978355db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/backend/web/index.php?r=lembaga%2Findex</value>
      <webElementGuid>b044b56b-b6ae-4eb3-a385-47dc4dee50a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tampilkan Semua</value>
      <webElementGuid>9238845b-d39d-4276-9fdd-2d09bb72c70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w0&quot;)/div[@class=&quot;card-header p-2&quot;]/a[@class=&quot;btn btn-info&quot;]</value>
      <webElementGuid>28d6da00-1492-4e76-95fd-158d3849f6ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/a</value>
      <webElementGuid>452807d3-18e2-453a-9030-223d99bfcabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tampilkan Semua')]</value>
      <webElementGuid>d69b11f8-8295-4f72-ada7-6afc60e1b32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terapkan Pencarian'])[1]/following::a[1]</value>
      <webElementGuid>4abfcfff-0ed5-46ae-8247-8d7c00722bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lembaga'])[5]/following::a[1]</value>
      <webElementGuid>6f523278-b07d-4404-9085-52ed355a5b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Lembaga'])[1]/preceding::a[1]</value>
      <webElementGuid>85f08bc6-7d22-4ba3-b669-c236f41ab205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/preceding::a[2]</value>
      <webElementGuid>a8844f2d-9657-4e96-ba59-0153f5ec2e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tampilkan Semua']/parent::*</value>
      <webElementGuid>b19625a9-9678-4fb5-9add-53b86e2dbea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/backend/web/index.php?r=lembaga%2Findex')])[2]</value>
      <webElementGuid>2e5a89e5-2b0a-4c1d-853c-462a6fbc2792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/a</value>
      <webElementGuid>48c27f89-4d39-4847-af28-d44123d0efc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/backend/web/index.php?r=lembaga%2Findex' and (text() = ' Tampilkan Semua' or . = ' Tampilkan Semua')]</value>
      <webElementGuid>f7eebb58-1dff-41ea-b44a-8fc2417a3eeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
