<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>2095b8ed-1f34-43ad-bde4-75d2f09b846a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='data']/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.pagination > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>632332c9-0f58-4f78-97da-a4799bbc48be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/backend/web/index.php?r=mustahik%2Findex&amp;page=2</value>
      <webElementGuid>dde05963-fa79-4650-be91-fe57093e200c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-page</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c50c9564-cee2-4d5e-b9c9-e1a681480064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6e3fb3d5-ad15-48cd-8d3c-57fa4f88153b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data&quot;)/ul[@class=&quot;pagination&quot;]/li[4]/a[1]</value>
      <webElementGuid>7e89ac08-b61b-4f3f-ae2f-0b85b3d578fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data']/ul/li[4]/a</value>
      <webElementGuid>89de3f96-c6c4-43a6-a09f-553310b7c13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>8e755690-e1f7-4af7-be49-9ad11166c074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[1]/following::a[2]</value>
      <webElementGuid>9d182110-80d0-46dc-9b55-0ae36964f759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pertama'])[1]/following::a[2]</value>
      <webElementGuid>d5ef14a0-1ca2-4433-9059-1e4d0e238972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='»'])[1]/preceding::a[9]</value>
      <webElementGuid>fca867ee-4c1a-4ba4-b3ff-9ddfce015454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terakhir'])[1]/preceding::a[10]</value>
      <webElementGuid>9223b9a6-68d8-4cb6-9484-61409842b7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/backend/web/index.php?r=mustahik%2Findex&amp;page=2')]</value>
      <webElementGuid>5c12ac6a-891a-4353-8768-4a9b37915b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]/a</value>
      <webElementGuid>f1d1ba94-967c-4630-b650-666a340038aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/backend/web/index.php?r=mustahik%2Findex&amp;page=2' and (text() = '2' or . = '2')]</value>
      <webElementGuid>8b35fba1-7ea2-40fc-8cc1-2d439db3e1f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
