<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pertama</name>
   <tag></tag>
   <elementGuidId>4328a1bc-c07c-44e0-8a81-f9482b9592f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='data']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.first > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d37a19ed-d279-4c09-be09-1c1e13f81a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/backend/web/index.php?r=mustahik%2Findex&amp;page=1</value>
      <webElementGuid>7c4c14cc-419c-47e5-90d7-d438d09a69d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-page</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a8bb56c0-1403-420e-9e25-4098e8073f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pertama</value>
      <webElementGuid>b91c674f-bf5d-4d6b-a509-11207d9f9a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data&quot;)/ul[@class=&quot;pagination&quot;]/li[@class=&quot;first&quot;]/a[1]</value>
      <webElementGuid>0bb4eba3-8c34-4a8b-8b55-f021d234f049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data']/ul/li/a</value>
      <webElementGuid>97120bad-6b06-4582-a3a7-0607e9e1a001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pertama')]</value>
      <webElementGuid>51583013-60fd-40df-a6d5-b2f93f128bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAWA TENGAH'])[2]/following::a[1]</value>
      <webElementGuid>bfa41053-835e-440b-b462-7a46f9d02d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA SEMARANG'])[2]/following::a[1]</value>
      <webElementGuid>96fde039-6270-485a-b207-06097489a848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[1]/preceding::a[1]</value>
      <webElementGuid>01d003c7-34d3-4244-a2f9-af75204a46f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='»'])[1]/preceding::a[12]</value>
      <webElementGuid>4cdcc8fd-961d-4c32-991e-2df914d7b507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pertama']/parent::*</value>
      <webElementGuid>b5d10d18-cd20-416f-941e-10c896104b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/backend/web/index.php?r=mustahik%2Findex&amp;page=1')]</value>
      <webElementGuid>5f9facba-3fd3-42c7-95de-2aad1a36df51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li/a</value>
      <webElementGuid>5db227d0-ff6f-484f-992a-845f109e24b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/backend/web/index.php?r=mustahik%2Findex&amp;page=1' and (text() = 'Pertama' or . = 'Pertama')]</value>
      <webElementGuid>9b6bba1c-ae8e-4c8d-aabf-07fcaef77ea9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
