<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Terakhir</name>
   <tag></tag>
   <elementGuidId>2c1bef4e-45c9-4cc1-bcda-64e52ac69f55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='data']/ul/li[14]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.last</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>78b0ac55-46cb-4198-abcc-b89c1ec580eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>last</value>
      <webElementGuid>ebbf855a-aa05-4be2-aeaa-2ce3b08bc6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terakhir</value>
      <webElementGuid>50d732c2-935f-45cd-b85e-2a1b67f056f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data&quot;)/ul[@class=&quot;pagination&quot;]/li[@class=&quot;last&quot;]</value>
      <webElementGuid>add3c338-fd37-4354-a3f2-b708aa3d083d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data']/ul/li[14]</value>
      <webElementGuid>a6ab2246-b6d0-46d3-97bd-5f5fdbdad3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='»'])[1]/following::li[1]</value>
      <webElementGuid>fc411388-d520-4a4c-9d7a-de8ce07030d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[1]/following::li[12]</value>
      <webElementGuid>ad4e2f26-d8bd-4ffd-89e6-61551e799d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[14]</value>
      <webElementGuid>b3f92062-f4c1-4eee-844f-7773e9533156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Terakhir' or . = 'Terakhir')]</value>
      <webElementGuid>a6786581-79a2-4cde-8130-c954488ac828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
