<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_RB-0722U10EKOPENVII2024</name>
   <tag></tag>
   <elementGuidId>d655a152-5f9b-4f13-a0c8-ae1b23bad405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='data']/table/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;RB-0722/U10/EKOPEN/VII/2024&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d8226f59-4ea7-40e3-aa28-e220b7ff3e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RB-0722/U10/EKOPEN/VII/2024</value>
      <webElementGuid>92b42edb-850b-4b95-92c8-f523dea8f418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data&quot;)/table[@class=&quot;table table-hover&quot;]/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>bf377f0d-8abf-4426-a9f3-0762a981af14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data']/table/tbody/tr/td[3]</value>
      <webElementGuid>8d803e84-bd9c-4fc2-9823-02b3f499e04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DONE'])[2]/following::td[1]</value>
      <webElementGuid>7055ef0e-6e65-4386-be75-4a6c0d3052c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Unit'])[1]/following::td[3]</value>
      <webElementGuid>d8f4b10d-157c-4a11-a70c-ff9c5eac09be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp. 6.160.000'])[1]/preceding::td[3]</value>
      <webElementGuid>ed4795cd-8cb1-4389-ac63-b9c7dd8b8c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RB-0722/U10/EKOPEN/VII/2024']/parent::*</value>
      <webElementGuid>8da55f77-24c6-4926-a14a-1c68b583e8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>59dd4c2a-8e8d-4ce9-b850-c053d278048c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'RB-0722/U10/EKOPEN/VII/2024' or . = 'RB-0722/U10/EKOPEN/VII/2024')]</value>
      <webElementGuid>80453d60-f7aa-4202-b2d3-93d8f2e361b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
