<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nomor Usulan</name>
   <tag></tag>
   <elementGuidId>620ecfbc-bfd3-440b-bb03-30ffff6e0e3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='data']/table/thead/tr/th[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ececa078-fa01-4ce2-a554-1eb9a04db227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/backend/web/index.php?r=bantuan-usulan%2Findex&amp;sort=nomor_usulan</value>
      <webElementGuid>3a316633-ef33-4150-97a1-c917735c97f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sort</name>
      <type>Main</type>
      <value>nomor_usulan</value>
      <webElementGuid>9be0493f-eaf9-422c-91dd-684a00b8d1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomor Usulan</value>
      <webElementGuid>d0ca3784-1d7d-4748-84b4-24c8d94c458c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data&quot;)/table[@class=&quot;table table-hover&quot;]/thead[1]/tr[1]/th[3]/a[1]</value>
      <webElementGuid>ca409c67-7890-4b9c-8626-9d265c50596a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data']/table/thead/tr/th[3]/a</value>
      <webElementGuid>b7d516ad-ffde-47e9-960b-9638691c2726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Nomor Usulan')]</value>
      <webElementGuid>77177286-fd3c-4dad-b0f7-620e05a7d82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::a[1]</value>
      <webElementGuid>6c7fb93f-a27d-4b81-a2ec-37e633547f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[1]/following::a[1]</value>
      <webElementGuid>35fc0c7e-727c-4619-92b0-fb32a8270c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Judul Bantuan'])[2]/preceding::a[1]</value>
      <webElementGuid>cf946922-5429-40b6-acd8-59f024c3f430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Usulan'])[1]/preceding::a[1]</value>
      <webElementGuid>991f126c-b5ad-4015-92a1-010cc0c0af5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/backend/web/index.php?r=bantuan-usulan%2Findex&amp;sort=nomor_usulan')]</value>
      <webElementGuid>6de2a910-8899-4406-9270-947e95492ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/a</value>
      <webElementGuid>43015366-8f97-4249-870d-1e6ac032543a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/backend/web/index.php?r=bantuan-usulan%2Findex&amp;sort=nomor_usulan' and (text() = 'Nomor Usulan' or . = 'Nomor Usulan')]</value>
      <webElementGuid>2ab53672-d85d-4a97-83e3-cd2e1769a3e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
