<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>78314d44-3665-467f-81e4-8e652c00f681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='data']/ul/li[10]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.next > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e9bc80a-edeb-4148-8b6e-a322b82598a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/backend/web/index.php?r=bantuan-pencairan%2Findex&amp;page=2</value>
      <webElementGuid>3a00acab-095c-45d8-8abb-82356d5511a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-page</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>28743601-0d18-4e03-ae84-1c74bd50eca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>»</value>
      <webElementGuid>801edad8-7335-4cc6-9f1c-e569053589f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data&quot;)/ul[@class=&quot;pagination&quot;]/li[@class=&quot;next&quot;]/a[1]</value>
      <webElementGuid>18153018-8c4a-45a6-b573-1fd703ff864f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data']/ul/li[10]/a</value>
      <webElementGuid>a0eb45d1-d552-4a20-989c-400ee68d0d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'»')]</value>
      <webElementGuid>1e2d9074-da6e-4879-bc50-177fb3015db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[1]/following::a[9]</value>
      <webElementGuid>dd8950e4-d146-44f8-a3ad-87219a7fd238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit PLN Pusat'])[21]/following::a[9]</value>
      <webElementGuid>453987cc-6e9b-40f7-8910-47fa86388a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PeTIK Jombang'])[1]/preceding::a[1]</value>
      <webElementGuid>9b5f3ac6-3bce-4333-ade0-8da83613670b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='»']/parent::*</value>
      <webElementGuid>6e4d5835-8ee3-42ed-9724-dfcffcfe279e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/backend/web/index.php?r=bantuan-pencairan%2Findex&amp;page=2')])[2]</value>
      <webElementGuid>58e81b90-bb84-4d1c-ae84-8ee2bd9418f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>a422ab87-1d47-421e-96f1-d1e613ddf6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/backend/web/index.php?r=bantuan-pencairan%2Findex&amp;page=2' and (text() = '»' or . = '»')]</value>
      <webElementGuid>ce3fc0c0-87e8-48e3-b677-bdc63d5d59f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
