<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nomor Realisasi Dana</name>
   <tag></tag>
   <elementGuidId>a2e9e94c-4376-48d6-b1b8-cf5c232cdee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='data']/table/thead/tr/th[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1975fbd2-bbda-4d92-b39d-aee5c6c70af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/backend/web/index.php?r=bantuan-pencairan%2Findex&amp;sort=nomor_pencairan</value>
      <webElementGuid>397ca957-2268-4153-8143-57d448aeb562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sort</name>
      <type>Main</type>
      <value>nomor_pencairan</value>
      <webElementGuid>43f41cdb-09d5-420d-a147-5335fe326bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomor Realisasi Dana</value>
      <webElementGuid>b5d8b339-8c94-479c-a00f-78c11e6f5c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data&quot;)/table[@class=&quot;table table-hover&quot;]/thead[1]/tr[1]/th[3]/a[1]</value>
      <webElementGuid>e04caea5-b1ca-4ae4-9de0-1b5e0141e2b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data']/table/thead/tr/th[3]/a</value>
      <webElementGuid>2e1ac18e-f64a-4b2a-af99-40aed5a0ff91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Nomor Realisasi Dana')]</value>
      <webElementGuid>fb074ecb-782f-49e5-a6ec-893856b2d53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::a[1]</value>
      <webElementGuid>261f4db1-862b-4195-9ef9-8a1bc7dd75b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[1]/following::a[1]</value>
      <webElementGuid>ac62144a-0d3e-4278-a67c-617da8543db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Judul Bantuan'])[2]/preceding::a[1]</value>
      <webElementGuid>d2548d29-7532-439c-94f7-3fe9fcfd71da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Pencairan'])[1]/preceding::a[1]</value>
      <webElementGuid>00edae47-3085-46be-81fa-c2703d982e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nomor Realisasi Dana']/parent::*</value>
      <webElementGuid>ea22d102-aa98-4fac-b338-79939bb49ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/backend/web/index.php?r=bantuan-pencairan%2Findex&amp;sort=nomor_pencairan')]</value>
      <webElementGuid>c65fbc6c-4b6b-4ba7-838f-088f0376c94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/a</value>
      <webElementGuid>6f0b22aa-1ccf-4c9d-b522-0f6a3eb1d195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/backend/web/index.php?r=bantuan-pencairan%2Findex&amp;sort=nomor_pencairan' and (text() = 'Nomor Realisasi Dana' or . = 'Nomor Realisasi Dana')]</value>
      <webElementGuid>2170d940-0fb3-4bc1-9cf3-e8dfb9f56a18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
