<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal Minimal_UnitApprovalnominal_minimal</name>
   <tag></tag>
   <elementGuidId>f439e352-6295-441c-869e-8a43a7d1f323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unitapproval-nominal_minimal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unitapproval-nominal_minimal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18711c70-5be2-428c-a7cc-942dd1519332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4c36b5d5-1749-4eca-beee-38e14a8fe246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitapproval-nominal_minimal</value>
      <webElementGuid>2fb0ff51-6fdd-4eca-8fb8-69bc718bae45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a2b4607f-8281-41a7-aa3a-72b5e37074e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UnitApproval[nominal_minimal]</value>
      <webElementGuid>d6d375df-2fc9-4b22-8725-2c18385e5e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de073d7d-bfe1-46d9-a934-c745f4d3fd6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unitapproval-nominal_minimal&quot;)</value>
      <webElementGuid>96f7b16d-371f-47ab-b030-5cd2a505b07d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unitapproval-nominal_minimal']</value>
      <webElementGuid>2453e5ae-1068-4691-b535-0c6ad2070dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[3]/input</value>
      <webElementGuid>be317072-436a-4a97-882e-100d39c8b069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>7eef096f-fed8-41c6-ad4c-469496ddab1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'unitapproval-nominal_minimal' and @name = 'UnitApproval[nominal_minimal]']</value>
      <webElementGuid>7c7ffd04-50a3-451c-ba17-492a74a3732e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
