<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal Minimal_UnitApprovalnominal_minimal</name>
   <tag></tag>
   <elementGuidId>f439e352-6295-441c-869e-8a43a7d1f323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unitapproval-nominal_minimal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unitapproval-nominal_minimal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nominal Minimal&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b26f1860-d0f7-4c94-9de6-52f2d5b058e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3dc13b04-34e1-44b7-9c5c-c7898d161284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitapproval-nominal_minimal</value>
      <webElementGuid>f6868c05-388c-409e-a47c-ee7d77fd935b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1d6579ce-f65a-4333-8790-1147c69c8907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UnitApproval[nominal_minimal]</value>
      <webElementGuid>199f5a74-9581-40ee-baa6-bc37a250a0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>643c3de7-ac6f-4169-a421-ad0639dd48a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unitapproval-nominal_minimal&quot;)</value>
      <webElementGuid>9fa03b63-3017-4a60-99fe-f22316bfd0e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unitapproval-nominal_minimal']</value>
      <webElementGuid>d0128a82-cae2-4b53-8603-034382067f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[3]/input</value>
      <webElementGuid>16d096f8-27cc-4448-91ab-435d208671bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>e6bb00d5-27f9-4153-b237-53e9989ea62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'unitapproval-nominal_minimal' and @name = 'UnitApproval[nominal_minimal]']</value>
      <webElementGuid>06a9ddb4-07a6-4c03-bc16-f8d46b024fe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
