<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_Bantuantelepon_pengaju</name>
   <tag></tag>
   <elementGuidId>a924421a-dff0-42a9-95cc-062b30bbcf8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-telepon_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-telepon_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba518ce7-24b2-425f-8f84-0f5ff7c0b4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>196230b1-1521-43c9-a61d-8d1b70dac442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-telepon_pengaju</value>
      <webElementGuid>4bdb93f1-8892-4e5b-817b-3d17d4f7f410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bcb755ae-01ca-4655-b71b-495f9bbdcba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[telepon_pengaju]</value>
      <webElementGuid>e0a50ff4-d22d-4f59-8ea1-46901c28d411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>0cc3639a-6f54-4db3-9c67-e6ce88c2405b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-telepon_pengaju&quot;)</value>
      <webElementGuid>7fe713b1-baac-49a4-ac4b-be0396168bef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-telepon_pengaju']</value>
      <webElementGuid>773b079c-bb35-4438-b08f-d254711d37cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-perorangan']/div[4]/div[2]/div/input</value>
      <webElementGuid>190a96fb-af65-4a7d-9494-06d1d3e3f16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div[2]/div/input</value>
      <webElementGuid>2f347e63-011d-479c-8410-1768341fc9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-telepon_pengaju' and @name = 'Bantuan[telepon_pengaju]']</value>
      <webElementGuid>6bb851fd-6c19-46f7-9810-e878af96b5aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
