<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Pemilik_Bantuanbank_pemilik_pengaju (1)</name>
   <tag></tag>
   <elementGuidId>7a93baef-f2c9-4818-bc70-2c2a14af1e4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-bank_pemilik_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-bank_pemilik_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e39e3c2b-9c85-4454-bafe-f276b7a067fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7284fa8-60e4-47dc-bbd1-91c2858bdf5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-bank_pemilik_pengaju</value>
      <webElementGuid>e83fda8d-b27e-43d9-9099-b3da59963004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bdd46d1a-4bb2-4f97-8678-91107286b556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[bank_pemilik_pengaju]</value>
      <webElementGuid>3e318d51-1aff-4756-8da2-0d8fdcafde68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>b19ab8a7-f48a-4f43-a93a-c14235ad9e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-bank_pemilik_pengaju&quot;)</value>
      <webElementGuid>13e57ab2-e186-423e-85a9-c7b6273d6d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-bank_pemilik_pengaju']</value>
      <webElementGuid>5f0c577f-7022-40af-a402-b5d036df6700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div[2]/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>73fda8aa-a0c4-40ef-84c9-1d7921bcb5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>d3ca2bbe-d58f-4673-958f-607cfd3c7a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-bank_pemilik_pengaju' and @name = 'Bantuan[bank_pemilik_pengaju]']</value>
      <webElementGuid>7c345325-0063-4552-86e5-9265f0593137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
