<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_Bantuantelepon_pengaju (3)</name>
   <tag></tag>
   <elementGuidId>fc02e657-8e83-4f66-aec9-2697ec2fb8f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-telepon_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-telepon_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45dee4c2-c44a-44db-834d-4e72ec834c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1251366-91a9-452c-a196-1813bae37d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-telepon_pengaju</value>
      <webElementGuid>5f983880-b564-457e-ba12-e22bee192325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>49cd6cba-5c67-430b-97c1-4b8842a060d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[telepon_pengaju]</value>
      <webElementGuid>b7cc216b-3600-4bde-bcac-72b25b74cf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>65e06458-7b3f-48e1-8656-d3b665050493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-telepon_pengaju&quot;)</value>
      <webElementGuid>ead38559-88f4-438e-a1fb-4899f7fcf064</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-telepon_pengaju']</value>
      <webElementGuid>8b6ac63d-b73f-4d9e-a42f-4abcf353c787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-perorangan']/div[4]/div[2]/div/input</value>
      <webElementGuid>3f24d7a0-8f43-4188-b2a0-c49066a2dce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div[2]/div/input</value>
      <webElementGuid>52ec164e-fd18-4553-b535-4eb27134a432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-telepon_pengaju' and @name = 'Bantuan[telepon_pengaju]']</value>
      <webElementGuid>9f078f57-b77f-48da-8e6b-0249bfc7abc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
