<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_Bantuantelepon_pengaju (4)</name>
   <tag></tag>
   <elementGuidId>9c193cb4-8501-401a-9489-692e374ce3c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-telepon_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-telepon_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eefd0de3-e787-4cb1-a701-3470c94fc62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3603d23-f278-4e18-9158-c8ecb5dccb0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-telepon_pengaju</value>
      <webElementGuid>02dfc026-5367-4af8-b556-c91e0f5d3b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2e641269-43b9-4288-9f77-050539d05c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[telepon_pengaju]</value>
      <webElementGuid>9d9ccef5-a9a8-4198-8a82-9c8e3643fbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>ee87657f-b037-42fb-b5cf-df785812f4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-telepon_pengaju&quot;)</value>
      <webElementGuid>4da5ec3e-dbc1-48f4-943e-b3ac93262e55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-telepon_pengaju']</value>
      <webElementGuid>405cc9eb-29e7-4054-9c8b-71d144f6f208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-perorangan']/div[4]/div[2]/div/input</value>
      <webElementGuid>3bd1e4f7-eb49-4030-9562-10ef68d03bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div[2]/div/input</value>
      <webElementGuid>7dec1eee-5a66-48aa-adf4-47829f777b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-telepon_pengaju' and @name = 'Bantuan[telepon_pengaju]']</value>
      <webElementGuid>20ce945d-ebd0-4765-a200-50d27305acb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
