<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Rekening_Bantuanbank_rekening_pengaju (2)</name>
   <tag></tag>
   <elementGuidId>7705c8da-ae90-48f4-ac59-04027f495595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-bank_rekening_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-bank_rekening_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb71a727-7aef-4ea6-ac9a-60ec6edd6875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b685998-b5f8-4a41-896d-d1315213feb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-bank_rekening_pengaju</value>
      <webElementGuid>f2c47b1a-0c23-475f-b108-cad5b36f6a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fdac4ed3-b08a-4f66-89d5-2b3c9cd0c7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[bank_rekening_pengaju]</value>
      <webElementGuid>46d232d7-4a71-44f0-af08-b74aa69f1d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>6976b75e-bf41-461a-b18d-ecb7769cef1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-bank_rekening_pengaju&quot;)</value>
      <webElementGuid>a548ccbc-715b-4830-8d8d-053818a2b360</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-bank_rekening_pengaju']</value>
      <webElementGuid>473a1033-4d6e-4672-8f1a-862398785954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div[2]/div/div/div[6]/div[2]/div/input</value>
      <webElementGuid>62653b44-248b-44aa-b0ab-ed44d52d118d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[6]/div[2]/div/input</value>
      <webElementGuid>5ee30ae5-ce2c-48c8-a011-d7e8a38cc93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-bank_rekening_pengaju' and @name = 'Bantuan[bank_rekening_pengaju]']</value>
      <webElementGuid>ab0aede5-b8d3-40be-801b-2ec6dce49f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
