<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_Bantuanemail_pengaju (3)</name>
   <tag></tag>
   <elementGuidId>78832e93-4b44-4942-9936-1eb1c99891c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-email_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-email_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33fc6756-ae9f-479b-a376-09a48d152ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b30819fa-19de-46ba-bb7c-79e21fc22669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-email_pengaju</value>
      <webElementGuid>b8a2a819-1663-4c42-94c0-7b2e3862fb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ea0ec055-6c00-40f3-9b52-14c30670fa71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[email_pengaju]</value>
      <webElementGuid>f5231e6e-9874-4464-a90c-250e92e60afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>6d820c06-11c6-46f6-81e9-85a84a574d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-email_pengaju&quot;)</value>
      <webElementGuid>8cd0f7b8-ce50-400a-8e93-a9286e098ec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-email_pengaju']</value>
      <webElementGuid>241fa719-116e-4833-abad-dbe9727d7835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-perorangan']/div[5]/div[2]/div/input</value>
      <webElementGuid>9e3221a6-ef29-4039-83d4-a2d55cc5ddac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/div[2]/div/input</value>
      <webElementGuid>a8e06872-c811-48b0-bb06-82dd23eac80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-email_pengaju' and @name = 'Bantuan[email_pengaju]']</value>
      <webElementGuid>180f08d9-8f24-40f6-b8cb-3167a57ade7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
