<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Pengaju_Bantuannama_pengaju</name>
   <tag></tag>
   <elementGuidId>129f0b79-de4e-4fa7-bd97-c76983247276</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-nama_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-nama_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed9709af-df0f-4e82-acb8-37106382edf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b77299b-3f34-46eb-a35c-f40fcb120169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-nama_pengaju</value>
      <webElementGuid>6326f3bb-8c69-4104-9c8e-d072690a5010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>43577cca-f90a-489a-ae36-968ac057c527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[nama_pengaju]</value>
      <webElementGuid>a34c996c-2b7c-4332-bb64-fb45a76e69dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>333ba619-0c32-4824-b107-b9174cefd385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-nama_pengaju&quot;)</value>
      <webElementGuid>49f580ec-77b9-46f4-8e63-e7c1b830d992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-nama_pengaju']</value>
      <webElementGuid>3e48caa1-bc42-4c7e-b718-53521e9ff85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-perorangan']/div[2]/div[2]/div/input</value>
      <webElementGuid>69e6974e-f567-4970-8c51-2f81a9101666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>ddb1e8ec-9d60-41d2-bd51-ce5f7c8da96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-nama_pengaju' and @name = 'Bantuan[nama_pengaju]']</value>
      <webElementGuid>0dc5abf7-2557-4ce3-b2b0-156d4abeff13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
