<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_Bantuantelepon_referensi (1)</name>
   <tag></tag>
   <elementGuidId>deb2aed9-94e6-4b54-960d-a47d17a3e9a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-telepon_referensi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-telepon_referensi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b0adc48-5de1-41c2-8940-af67ffc0adcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5941cac6-c95f-4c27-ad32-31678c71fa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-telepon_referensi</value>
      <webElementGuid>3873ac17-3dfd-42ad-a8a2-91d3e8d9c628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d8152e3a-8c1b-4b04-86b9-9d7c5618da5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[telepon_referensi]</value>
      <webElementGuid>c77ff235-551e-42b7-8646-4e07c8a03d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>c1376e40-49d6-4c51-ba6a-530243f16947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-telepon_referensi&quot;)</value>
      <webElementGuid>96ec1c2d-feee-4d6c-b669-081af9d2cdc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-telepon_referensi']</value>
      <webElementGuid>218860f9-61a1-4eb7-836a-8eb6ee4f5533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div[2]/div/div/div[10]/div[2]/div/input</value>
      <webElementGuid>11b30381-051d-4aa1-9044-e6451c2cc13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[10]/div[2]/div/input</value>
      <webElementGuid>b2d01c06-4833-417d-b70d-4878c1f1c54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-telepon_referensi' and @name = 'Bantuan[telepon_referensi]']</value>
      <webElementGuid>303b2282-0c5e-4919-acda-9e3b0c6a34fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
