<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_Bantuantelepon_referensi (3)</name>
   <tag></tag>
   <elementGuidId>2b92baf9-cc82-47bf-abb2-71032dd9571a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-telepon_referensi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-telepon_referensi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66eee432-71f0-4bdf-86d5-b0ce7228ff43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9949085-76a3-4944-a33f-e49c610b2df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-telepon_referensi</value>
      <webElementGuid>41cae725-84a2-41dd-91bd-c6a3fef2a360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d6c9f2be-36cc-4c97-9611-c1f09135e616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[telepon_referensi]</value>
      <webElementGuid>245a3e9b-864f-4db7-af6b-de30a06590a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>d21b4fa4-2d1e-498b-8686-ab962dab0fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-telepon_referensi&quot;)</value>
      <webElementGuid>d00a26ce-e228-430f-b9a4-5791e50a1aa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-telepon_referensi']</value>
      <webElementGuid>5ffadd6e-628c-405c-9c08-24b031e10fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div[2]/div/div/div[10]/div[2]/div/input</value>
      <webElementGuid>9b604b27-22de-4e37-9e2f-bf69cb5bba40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[10]/div[2]/div/input</value>
      <webElementGuid>308f0e0d-9a60-420d-b88c-f6e82340df50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-telepon_referensi' and @name = 'Bantuan[telepon_referensi]']</value>
      <webElementGuid>72aa3b01-d360-4183-991e-dc0fba316ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
