<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Rekening_Bantuanbank_rekening_pengaju (3)</name>
   <tag></tag>
   <elementGuidId>4beb1391-edb1-45c3-9d0c-f3ea1785751b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-bank_rekening_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-bank_rekening_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>476a07c1-7d4e-481d-9382-242aa5de3087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b951b91f-9fc8-46fc-827a-017d4ab50b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-bank_rekening_pengaju</value>
      <webElementGuid>0d4f1996-ccea-4151-8c4b-ef082c34c499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6e70afcf-0fdb-4dce-9f98-2b45ceffe68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[bank_rekening_pengaju]</value>
      <webElementGuid>8a1361df-7973-4e8e-9a38-0af1dd1276c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>3c8a27bb-ae11-450a-9796-456e2c837b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-bank_rekening_pengaju&quot;)</value>
      <webElementGuid>980b6d17-a344-491f-a739-90a5e06276d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-bank_rekening_pengaju']</value>
      <webElementGuid>cf667a60-0029-4aa3-a976-b6d045f18b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div[2]/div/div/div[6]/div[2]/div/input</value>
      <webElementGuid>bcaece6b-a38e-4845-af21-a948c09cd5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[6]/div[2]/div/input</value>
      <webElementGuid>c32f2a4b-8503-4cfe-8a00-c8bd436b3d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-bank_rekening_pengaju' and @name = 'Bantuan[bank_rekening_pengaju]']</value>
      <webElementGuid>821f2e74-63cf-4180-a9b9-e7130ccd6c46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
