<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Referensi_Bantuannama_referensi</name>
   <tag></tag>
   <elementGuidId>6f702584-4b51-4fab-9809-8e721cf4ac87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-nama_referensi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-nama_referensi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bantuan-nama_referensi</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9625de8b-fa26-48ec-a438-fa48fdcced8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>573b1d1c-ef92-489c-b31d-49e2b7fb8fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-nama_referensi</value>
      <webElementGuid>21329898-d791-46cc-88ed-cc61f0d14a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2a17de76-3f3a-4128-859f-ac02aefa87b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[nama_referensi]</value>
      <webElementGuid>6a6a6857-5dce-4cde-b1ff-b11a28a3779c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>2a4b192f-6bf4-4769-86ea-2ea27edad9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-nama_referensi&quot;)</value>
      <webElementGuid>a4a9e8a7-0be0-49bb-9a27-d5f646774d9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-nama_referensi']</value>
      <webElementGuid>c4cddb85-d03f-4d95-83e5-95532c3892e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[3]/div[2]/div/div/div[8]/div[2]/div/input</value>
      <webElementGuid>4729834e-0acf-483f-8f5b-c8fe7f41b0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[8]/div[2]/div/input</value>
      <webElementGuid>a8c3ed99-611a-44b1-8e4a-ac536e410a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-nama_referensi' and @name = 'Bantuan[nama_referensi]']</value>
      <webElementGuid>b2e54afe-560e-4d92-891a-3ecba6e8afd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div[2]/div/div/div[8]/div[2]/div/input</value>
      <webElementGuid>85a58c58-3c95-45fa-90d1-488ff6d9c644</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
