<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Pemilik_Bantuanbank_pemilik_pengaju</name>
   <tag></tag>
   <elementGuidId>7935cc9e-091b-4d84-b75a-7246994b7f4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-bank_pemilik_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-bank_pemilik_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bantuan-bank_pemilik_pengaju</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89640f95-f0c6-4c6a-9cfa-17375ca87319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b9fbbd6-9231-42c9-9d3f-7738ccf7910f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-bank_pemilik_pengaju</value>
      <webElementGuid>2c74a15e-0308-40e1-b5ad-03ea75dc9f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1dc50bb0-2f11-4c5a-b0aa-13e09d3d47a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[bank_pemilik_pengaju]</value>
      <webElementGuid>ae6def45-1f87-4a3a-a9b8-62e9a73fb0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>7d593c19-43de-4f01-9e39-23e449da22e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-bank_pemilik_pengaju&quot;)</value>
      <webElementGuid>d6f16be2-1f29-40a0-bb58-816aa00dbf67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-bank_pemilik_pengaju']</value>
      <webElementGuid>261ba465-1440-4894-8c60-9486bc007f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[3]/div[2]/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>fafee39c-64ef-41e9-9283-3571b76fb6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>5560cb57-b244-4f56-b1f3-c68269ef2645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-bank_pemilik_pengaju' and @name = 'Bantuan[bank_pemilik_pengaju]']</value>
      <webElementGuid>9612ec8e-df2b-498b-af6f-6f50da167a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div[2]/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>9a2ab1ce-9175-48da-a21b-1901640a992a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>83dc1c5a-2a3c-4695-a653-a56db4d3629d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
