<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_Bantuanemail_pengaju (2)</name>
   <tag></tag>
   <elementGuidId>46350846-cb14-448b-8bdd-da1dfcd3b5dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-email_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-email_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd945b04-40b1-4fa3-ba7e-db8a1454a8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41d122b6-09ea-43b2-9a96-62684adb8a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-email_pengaju</value>
      <webElementGuid>73ced72b-832d-4256-929e-a6aa86f67e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>409e9cbc-7f66-4fa3-a713-6870ee5096d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[email_pengaju]</value>
      <webElementGuid>0afeffb2-d90f-4ce5-837e-ab1281937e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>0e689b4e-1215-49c7-acff-e0335be24c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-email_pengaju&quot;)</value>
      <webElementGuid>6a1fdfe8-752f-4439-9dc1-a9674250b254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-email_pengaju']</value>
      <webElementGuid>cda2234f-a52b-4315-b347-24344c8d3d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-perorangan']/div[5]/div[2]/div/input</value>
      <webElementGuid>8a91f062-8bf5-47db-8ec8-2b31f36e7864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/div[2]/div/input</value>
      <webElementGuid>8b0a88fb-023d-4348-a5f2-da3b0baa6819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-email_pengaju' and @name = 'Bantuan[email_pengaju]']</value>
      <webElementGuid>cd3dc88e-a4dd-469d-9c9c-69f0f5a2f438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
