<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK_Bantuannik_referensi</name>
   <tag></tag>
   <elementGuidId>9781645d-a3ec-4999-9df1-2849ec9ac5c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-nik_referensi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-nik_referensi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bantuan-nik_referensi</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4211c2d3-4c45-4a4e-9188-e364a819af3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bfc5f1a6-345b-46fb-8d04-dfe4a5a51ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-nik_referensi</value>
      <webElementGuid>77b48bdc-0b11-4a97-b4e1-a00a42782114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aa4209fd-50fe-4f62-bfcb-f680eed395e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[nik_referensi]</value>
      <webElementGuid>ac655dd3-0f40-4e37-bf6a-60723d4c0274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e9a299bb-53f6-4815-abf3-8581153897a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-nik_referensi&quot;)</value>
      <webElementGuid>def6ba42-501e-4800-96d0-721889549dd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-nik_referensi']</value>
      <webElementGuid>d0f28b85-131e-435f-9d42-fd3aaaa03157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[3]/div[2]/div/div/div[9]/div[2]/div/input</value>
      <webElementGuid>9b1debc0-75c1-4931-82f7-9901d864215c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[9]/div[2]/div/input</value>
      <webElementGuid>9b4471c4-c277-4d3a-8c2c-3a8340ce3aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-nik_referensi' and @name = 'Bantuan[nik_referensi]']</value>
      <webElementGuid>5a3f5c99-41d4-4960-8bdd-b5cc0a57a369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div[2]/div/div/div[9]/div[2]/div/input</value>
      <webElementGuid>beb2fd4e-26fb-4895-9a7b-fcb160caec3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/input</value>
      <webElementGuid>65c5563a-3c8b-412d-a4f0-718a159395d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
