<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Referensi_Bantuannama_referensi (1)</name>
   <tag></tag>
   <elementGuidId>a22482de-04e0-4e92-bb4a-83d1977ebd02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-nama_referensi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-nama_referensi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb7703ce-31cb-4c69-ba0a-873d40975fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e273233-c446-4b20-95c6-7534923442a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-nama_referensi</value>
      <webElementGuid>1674286d-d64c-43e5-b39a-f33d5486cb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2ffcb7f5-4a61-4acf-9bcd-24355009a4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[nama_referensi]</value>
      <webElementGuid>6f764e23-0a63-4c40-99de-395f86c81644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>270b0b8e-9885-414c-a219-3c287125084f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-nama_referensi&quot;)</value>
      <webElementGuid>6c0b7d36-9545-456d-a0e8-a2dd533b0e0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-nama_referensi']</value>
      <webElementGuid>3abe0a74-3de4-4f28-b46c-92878f491852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div[2]/div/div/div[8]/div[2]/div/input</value>
      <webElementGuid>7712e132-589b-4049-b437-484493dd402a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[8]/div[2]/div/input</value>
      <webElementGuid>17f125eb-bf59-41fc-9b0e-9faa2798c587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-nama_referensi' and @name = 'Bantuan[nama_referensi]']</value>
      <webElementGuid>bc202736-900f-4f20-9de1-944e2f5d46bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
