<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Rekening_Bantuanbank_rekening_pengaju</name>
   <tag></tag>
   <elementGuidId>0bec5c48-98b5-42e9-9355-9379b16cdfcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-bank_rekening_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-bank_rekening_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bantuan-bank_rekening_pengaju</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86ff52af-a8e2-4380-b696-569b04edb943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a0ddd0d-975d-4d91-8513-720f92ba6631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-bank_rekening_pengaju</value>
      <webElementGuid>45dcceef-6836-4189-8e0d-0c9ea04b123d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>427f3e82-056b-4a10-84b7-d6c8c3b15db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[bank_rekening_pengaju]</value>
      <webElementGuid>cd3d23d2-d31b-41dc-b6b0-d246844fcec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>1f0624b2-5f75-4e75-9553-553f72ed8e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-bank_rekening_pengaju&quot;)</value>
      <webElementGuid>7d2fc71a-52db-4259-b621-7c6cf4f4de74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-bank_rekening_pengaju']</value>
      <webElementGuid>03095d0c-0e92-46ab-95de-b6f0c79f4d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[3]/div[2]/div/div/div[6]/div[2]/div/input</value>
      <webElementGuid>8767415c-c348-459d-9d5c-c30b88548faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/input</value>
      <webElementGuid>6a29678e-0d14-496f-b89b-6b030c555205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-bank_rekening_pengaju' and @name = 'Bantuan[bank_rekening_pengaju]']</value>
      <webElementGuid>2176ea9c-49cd-4707-a654-2fb1089bb5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div[2]/div/div/div[6]/div[2]/div/input</value>
      <webElementGuid>6bbdf535-5c0d-4e28-9b3e-9530cdfa26d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[6]/div[2]/div/input</value>
      <webElementGuid>6f41c816-3995-4c50-81f5-bf771743f74e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
