<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK_Bantuannik_pengaju (3)</name>
   <tag></tag>
   <elementGuidId>037b41d8-7c64-4ade-a320-6fe62d89b933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuan-nik_pengaju']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-nik_pengaju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26eeb8d7-45cd-4491-bb04-8ba3f5154969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3f4e93b-9f74-45fb-bec6-46ba1825caba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-nik_pengaju</value>
      <webElementGuid>18b8577f-a5cc-4e70-a1a1-e4ebda9d756b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>240155da-3a92-47f3-8a0b-d00a7026d35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[nik_pengaju]</value>
      <webElementGuid>592361e4-14ec-41dd-865c-421341eb4c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e993e75b-6e88-4c54-a8cb-9748cc9ad458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-nik_pengaju&quot;)</value>
      <webElementGuid>81ba2808-2697-44f3-82b0-015a266e67cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuan-nik_pengaju']</value>
      <webElementGuid>84b1c37b-2d29-4ee8-90aa-54aec06e1042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-perorangan']/div[3]/div[2]/div/input</value>
      <webElementGuid>73f73b46-7b0b-4c58-8b71-4932af02b927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div/input</value>
      <webElementGuid>8002a64f-0a5c-4173-b35e-e677cd011a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bantuan-nik_pengaju' and @name = 'Bantuan[nik_pengaju]']</value>
      <webElementGuid>82029f0e-b01a-462f-b221-8fef25bd78e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
