<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih kategori --PERORANGANLEMBAGA (4)</name>
   <tag></tag>
   <elementGuidId>c53ca874-90fb-4bb6-85c9-2c1df7989222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='bantuan-kategori_penerima']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-kategori_penerima</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>203facc4-c2b1-4442-b8dd-04be2316249c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-kategori_penerima</value>
      <webElementGuid>6d8633be-8a20-472d-a82f-15f234457957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0fe9fc21-eb62-45cc-af5f-766f25ad2ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[kategori_penerima]</value>
      <webElementGuid>c5804480-263b-45a4-ada1-917b3d6b8a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
-- Pilih kategori --
PERORANGAN
LEMBAGA
</value>
      <webElementGuid>31d1ba64-e5d1-4cfa-aa05-42b663d7f6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-kategori_penerima&quot;)</value>
      <webElementGuid>b57e04ae-9697-4dc6-8c05-9d277254fab2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='bantuan-kategori_penerima']</value>
      <webElementGuid>87625132-42cb-4b1e-b57c-1a257bc54558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div[2]/div/div/div/div[2]/div/select</value>
      <webElementGuid>15d289cb-3df4-4d8b-a266-00a70bc91ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Kategori Pengaju'])[1]/following::select[1]</value>
      <webElementGuid>ad16b728-7c23-4e35-bef0-48677a57ab4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pengaju'])[1]/following::select[1]</value>
      <webElementGuid>71d7fa44-4f6c-4743-b100-c64bd0e75285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Pilih Lembaga'])[1]/preceding::select[1]</value>
      <webElementGuid>cd46b3f8-bf3d-4741-a271-c4cc12bd1138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Kategori Lembaga'])[1]/preceding::select[2]</value>
      <webElementGuid>989f8c47-7814-4bff-8f34-0116523565a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/select</value>
      <webElementGuid>377ca86c-88aa-4879-9e22-38b174a26711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'bantuan-kategori_penerima' and @name = 'Bantuan[kategori_penerima]' and (text() = '
-- Pilih kategori --
PERORANGAN
LEMBAGA
' or . = '
-- Pilih kategori --
PERORANGAN
LEMBAGA
')]</value>
      <webElementGuid>6197309a-217c-4683-a128-58a72f8f1629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
