<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi_Bantuandeskripsi (3)</name>
   <tag></tag>
   <elementGuidId>c889766e-d50b-485c-a7ea-d7ac42da3284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='bantuan-deskripsi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-deskripsi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4785a841-8b4a-4b1f-8595-5d119b3cc040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-deskripsi</value>
      <webElementGuid>393c8b67-a4a5-4adc-bf64-e8486246b72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>54ff838e-b68e-4814-8dcb-476e512425d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[deskripsi]</value>
      <webElementGuid>42a6d599-e969-4c5b-9039-2c78d06edc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4dcfaa0a-22c7-42e4-9286-c725bab1df5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-deskripsi&quot;)</value>
      <webElementGuid>53485b25-f889-485a-b895-c2f0d571c1f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='bantuan-deskripsi']</value>
      <webElementGuid>be10a867-ac79-4426-9b37-259ca1920899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/div/div/div[3]/div[2]/div/textarea</value>
      <webElementGuid>fb289c1f-4156-4ccf-b4ee-ba83f656b576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4c6cdd33-9867-4878-99b4-5e475a4feada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'bantuan-deskripsi' and @name = 'Bantuan[deskripsi]']</value>
      <webElementGuid>4b178b17-25ed-4f99-9b75-800f822e422b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
