<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Lokasi Penyaluran_Bantuanlokasi</name>
   <tag></tag>
   <elementGuidId>c1eb66a0-ebca-4afb-87df-b917d510d4c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='bantuan-lokasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-lokasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bantuan-lokasi</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c1a27336-c1b4-42c4-aa6f-6c349a993027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-lokasi</value>
      <webElementGuid>02e04fa1-6247-418b-9be7-40419ee33892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b309ee9f-38ea-49e7-a229-52c83c569d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[lokasi]</value>
      <webElementGuid>4c838612-09ec-4923-818f-0abee1d97dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ce9f8538-9721-4cd8-ad8d-c3dd92b1e023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-lokasi&quot;)</value>
      <webElementGuid>97e9f58f-4649-4338-a2b3-d8768ebb018b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='bantuan-lokasi']</value>
      <webElementGuid>2759c9b6-281a-4b3c-9571-8c52c7e14e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[3]/div/div/div/div[7]/div[2]/div/textarea</value>
      <webElementGuid>92e5983b-5410-43d0-ad26-72fe8c5570ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/textarea</value>
      <webElementGuid>e3ed84ad-1ed4-4f5f-96be-e94c77e573aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'bantuan-lokasi' and @name = 'Bantuan[lokasi]']</value>
      <webElementGuid>8bd3d5d0-47b1-4f16-bcc5-738a32dc12c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/div/div/div[4]/div[2]/div/textarea</value>
      <webElementGuid>15346218-75dd-42b9-9fe6-d399b494d9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/textarea</value>
      <webElementGuid>5ff38d11-3dad-4b6a-989c-47a588581ca2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
