<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi_Bantuandeskripsi (1)</name>
   <tag></tag>
   <elementGuidId>c1a8ee99-3ae7-4a2c-8bf1-a9589edb3b9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='bantuan-deskripsi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-deskripsi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>639471df-ef8a-4326-bb8d-e95cc94ed0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-deskripsi</value>
      <webElementGuid>aefd8dc5-fa5c-4164-9e7e-1499a423d95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>15193fa9-403b-4172-a2e2-3b496b980b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[deskripsi]</value>
      <webElementGuid>c81cf1b5-a2bb-4bb8-aa80-2672ee99707e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3891caf8-85f6-4ff0-a0f8-39d64532f634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-deskripsi&quot;)</value>
      <webElementGuid>f1388862-a670-41f7-a1a4-62edc1d1c2f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='bantuan-deskripsi']</value>
      <webElementGuid>58b54561-1eae-4227-9de2-d0f024f4700a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/div/div/div[3]/div[2]/div/textarea</value>
      <webElementGuid>fabae89e-65dc-4804-9a99-bbe8598290a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>86353a10-2aaa-4650-b7d0-48b0de505676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'bantuan-deskripsi' and @name = 'Bantuan[deskripsi]']</value>
      <webElementGuid>e30bb444-79eb-46ce-b082-dd5c19d6f410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
