<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Lokasi Penyaluran_Bantuanlokasi (3)</name>
   <tag></tag>
   <elementGuidId>4a036bc8-13d9-4eda-a045-dce904b36818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='bantuan-lokasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-lokasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5e021c36-37be-41f8-97d7-a9efc82d1827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-lokasi</value>
      <webElementGuid>36298bfb-3b19-4693-ab04-63d88c95e845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ca657ec1-f366-4f1d-93cf-97c31e79d3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[lokasi]</value>
      <webElementGuid>0f1f74d1-b0c9-4b39-8b89-b10cdd734953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>56fa0b57-4de1-45c6-9d06-aec9e207ad4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-lokasi&quot;)</value>
      <webElementGuid>56c4e0de-3bad-4fb5-b508-0466ec0a6270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='bantuan-lokasi']</value>
      <webElementGuid>84b2df5e-2d2b-42c3-979f-8ab6e87c191f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/div/div/div[4]/div[2]/div/textarea</value>
      <webElementGuid>815bac09-35ca-4a99-8994-6da0c62c65cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/textarea</value>
      <webElementGuid>a0f7d617-c310-48cc-b910-344dc70c5e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'bantuan-lokasi' and @name = 'Bantuan[lokasi]']</value>
      <webElementGuid>c708c739-a5d4-4c9c-b414-f28e3ea533cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
