<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi_Bantuandeskripsi (4)</name>
   <tag></tag>
   <elementGuidId>bce78672-b356-4e32-91d7-413f82165dd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='bantuan-deskripsi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-deskripsi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e7c924ac-81f8-4e1f-acc6-43fbfb994464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-deskripsi</value>
      <webElementGuid>6d51f651-daa7-42af-9323-94b9f5f90a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>36fed93a-652b-490e-a99a-c231c6434934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[deskripsi]</value>
      <webElementGuid>a337f95c-f75b-4c0b-bef8-2cb25346d909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ac0cc6d9-5ecc-42d2-a305-b79fbdc0e4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-deskripsi&quot;)</value>
      <webElementGuid>1eede89c-1d73-4761-8732-028a62c7b67b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='bantuan-deskripsi']</value>
      <webElementGuid>52e9201e-7d47-4915-a675-fd54eb92169a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/div/div/div[3]/div[2]/div/textarea</value>
      <webElementGuid>91733986-fca3-4b5e-a0c5-ed433b06e226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9aa34aef-a533-486d-984b-3c7936c21bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'bantuan-deskripsi' and @name = 'Bantuan[deskripsi]']</value>
      <webElementGuid>0fee5e13-8b1c-465b-9de2-ac591c2f2e0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
