<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Lokasi Penyaluran_Bantuanlokasi (2)</name>
   <tag></tag>
   <elementGuidId>ce7277b8-819b-413e-be32-78b32c2a3cca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='bantuan-lokasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuan-lokasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e387c188-6772-414c-b4a9-f78dfb4d2d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuan-lokasi</value>
      <webElementGuid>acddb2a2-a802-4750-9696-226c9109d4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b99daed0-ff57-4678-af10-2dab42e2d69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bantuan[lokasi]</value>
      <webElementGuid>afab5e9e-f722-4493-92cc-2572a668e132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9efd5c4e-4225-42e8-b4dc-cfb8f5b4c2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bantuan-lokasi&quot;)</value>
      <webElementGuid>168ac3b8-45c3-4248-8c08-17e6b5bea418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='bantuan-lokasi']</value>
      <webElementGuid>7c3cb202-9008-44ce-8e7e-dedfdb8d91a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/div/div/div[4]/div[2]/div/textarea</value>
      <webElementGuid>0e629c2a-a837-412c-8ffb-957760228d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/textarea</value>
      <webElementGuid>79b4cdcd-34e4-4211-8a1b-5b20bc0f9115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'bantuan-lokasi' and @name = 'Bantuan[lokasi]']</value>
      <webElementGuid>4fcaf751-ec21-4377-837c-2929c4be5417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
