<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Satellite</name>
   <tag></tag>
   <elementGuidId>fe61ba7d-e29e-4a2b-91b3-9661f843c8ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='557E4799-EC5E-4D60-AA3B-554852E99315']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#557E4799-EC5E-4D60-AA3B-554852E99315</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2116f391-6986-4b6b-9148-2e17b9c3f841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3b1e508-0165-4f92-b8b3-50f95ccb601c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show satellite imagery</value>
      <webElementGuid>b5f02d87-ab2f-47a2-86b8-3f4cea89970f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show satellite imagery</value>
      <webElementGuid>9cea4f60-aa2d-43e4-b348-8ecb6481962d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a95a7f1a-e44b-4210-854d-e85ce20f2d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitemradio</value>
      <webElementGuid>5e7e0931-681d-4ed5-8a4a-9f618df9915f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f33d9708-92be-4f5c-a587-cf6b10570c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cd0beb3d-0860-4138-968a-9631a8446708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>557E4799-EC5E-4D60-AA3B-554852E99315</value>
      <webElementGuid>21b8d60d-383c-4edd-b634-c3d5ed3d1be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Satellite</value>
      <webElementGuid>a07d59ad-c6d5-4a35-bdc6-cee12f2ea839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;557E4799-EC5E-4D60-AA3B-554852E99315&quot;)</value>
      <webElementGuid>9ddfed85-fe62-46e1-903d-db6e2a426c43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='557E4799-EC5E-4D60-AA3B-554852E99315']</value>
      <webElementGuid>8bc1e7a5-51d4-4cd7-95cc-c5b2890f35c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='map']/div/div[3]/div[3]/div/div[2]/button</value>
      <webElementGuid>0e17297e-ed20-4dfd-92bc-d5f3d288bd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrain'])[1]/following::button[1]</value>
      <webElementGuid>32bcaaaf-270f-47be-a743-8c82576207b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Map'])[1]/following::button[1]</value>
      <webElementGuid>07b0a391-94da-4e8b-b038-bc12c0225f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labels'])[1]/preceding::button[1]</value>
      <webElementGuid>0ccf5887-03dc-455f-91e4-c126fa9857dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyboard shortcuts'])[1]/preceding::button[8]</value>
      <webElementGuid>e0c30355-e85d-4a52-a49c-3b4899934eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Satellite']/parent::*</value>
      <webElementGuid>a7e583df-969d-4f9f-99c3-4cbc2ef180e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>8bd78df1-ca9c-4db3-a168-8c9d6430fbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Show satellite imagery' and @type = 'button' and @id = '557E4799-EC5E-4D60-AA3B-554852E99315' and (text() = 'Satellite' or . = 'Satellite')]</value>
      <webElementGuid>17989d30-cbd4-471a-ac01-42c6f1299986</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
