<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PB-1858U10EKOPENVII2024</name>
   <tag></tag>
   <elementGuidId>87e6f1bc-50b7-444c-9b78-2f14e36301cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-detail']/div/div/dl[4]/dd/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PB-1858/U10/EKOPEN/VII/2024&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a36dcc26-1216-4af3-bc23-5f0e53316088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/backend/web/index.php?r=bantuan%2Fview&amp;id=2589</value>
      <webElementGuid>c8292042-c0b1-43a8-b614-00fa86cc1a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PB-1858/U10/EKOPEN/VII/2024</value>
      <webElementGuid>f2dd795d-1cf4-41b1-ba99-55d5546a2ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-detail&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]/dl[@class=&quot;row&quot;]/dd[@class=&quot;col-sm-8&quot;]/a[1]</value>
      <webElementGuid>06e862dd-2640-486d-b446-af1222d5c1fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-detail']/div/div/dl[4]/dd/a</value>
      <webElementGuid>c17e174d-179a-4afb-8735-df0fd1362744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PB-1858/U10/EKOPEN/VII/2024')]</value>
      <webElementGuid>21f735f5-db31-427e-8bd0-6bafea8ce2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Pengajuan'])[1]/following::a[1]</value>
      <webElementGuid>22e3d771-4f50-456f-8e30-57f782471892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pengajuan'])[1]/following::a[1]</value>
      <webElementGuid>0c5bbe63-c824-4e31-8016-966ccf9e5343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Pengajuan'])[1]/preceding::a[1]</value>
      <webElementGuid>83e44bd3-44d6-400c-b3ce-adb3380666a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Pelaksanaan'])[1]/preceding::a[1]</value>
      <webElementGuid>08c74802-435a-4758-9abe-473e90ab65a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PB-1858/U10/EKOPEN/VII/2024']/parent::*</value>
      <webElementGuid>72217c50-19c0-49ac-8d9c-18f7049bb66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/backend/web/index.php?r=bantuan%2Fview&amp;id=2589')]</value>
      <webElementGuid>d1f6fa56-5b84-4880-8abe-60fea0c7b9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dl[4]/dd/a</value>
      <webElementGuid>ba26f4ec-8c28-42c4-b86a-4adb3c1d86a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/backend/web/index.php?r=bantuan%2Fview&amp;id=2589' and (text() = 'PB-1858/U10/EKOPEN/VII/2024' or . = 'PB-1858/U10/EKOPEN/VII/2024')]</value>
      <webElementGuid>6f8035ed-4a36-4f32-87e9-d7d095ecdc4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
