<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tambah Mustahik</name>
   <tag></tag>
   <elementGuidId>97446ea9-3b36-41a4-99ff-10c4d0d6fed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-detail']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9d6e863-95e6-4877-bc4f-10d902d9214a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mr-2</value>
      <webElementGuid>34979bb7-981f-4a59-ae54-977dc05bdd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/backend/web/index.php?r=bantuan-mustahik%2Fcreate&amp;id=2589&amp;from=USULAN&amp;idref=2116</value>
      <webElementGuid>b883d1c4-3e3f-45fa-b3d5-e4724b68cf01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah Mustahik</value>
      <webElementGuid>0d040adc-e3dd-4db6-bf8d-ad19d0c4c19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-detail&quot;)/a[@class=&quot;btn btn-primary mr-2&quot;]</value>
      <webElementGuid>24c174b8-8830-483c-893a-0a32c1414301</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-detail']/a</value>
      <webElementGuid>3d17eab1-d06e-4283-b295-187ec6a108a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tambah Mustahik')]</value>
      <webElementGuid>c52a549e-1fb1-4af2-a9f0-b2327139c2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Mustahik'])[5]/following::a[1]</value>
      <webElementGuid>f663b117-09b2-4182-872f-575a4d03cbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fi Sabilillah'])[6]/following::a[2]</value>
      <webElementGuid>23131de9-a652-4e30-a2d8-9f42e0d722f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import'])[1]/preceding::a[1]</value>
      <webElementGuid>44a8fe75-161f-4da6-9c3c-e80fb9198ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahap Approval'])[1]/preceding::a[2]</value>
      <webElementGuid>aa756dbc-6859-4e84-8683-bf8fe53d5513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Mustahik']/parent::*</value>
      <webElementGuid>e7a73fe9-738a-43c7-a581-50e745b0abbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/backend/web/index.php?r=bantuan-mustahik%2Fcreate&amp;id=2589&amp;from=USULAN&amp;idref=2116')]</value>
      <webElementGuid>995f6ea4-398c-446a-a17c-62a781427d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>6b1b4f0f-b647-4653-8e55-b54fe3727326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/backend/web/index.php?r=bantuan-mustahik%2Fcreate&amp;id=2589&amp;from=USULAN&amp;idref=2116' and (text() = ' Tambah Mustahik' or . = ' Tambah Mustahik')]</value>
      <webElementGuid>9b3cfd56-f4be-4e8a-8111-fe87412fb824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
