<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal Maksimal_UnitApprovalnominal__69293a</name>
   <tag></tag>
   <elementGuidId>d8c4d65f-7e56-463a-8438-f8dd4fbb9187</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unitapproval-nominal_maksimal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unitapproval-nominal_maksimal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c4c5996-7894-48d2-a3db-f16dda6d15f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d1e7ac71-6458-4413-86b4-560072ee7b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitapproval-nominal_maksimal</value>
      <webElementGuid>eb6a561f-4426-479c-abe4-bb1c87b7b3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>87bc0a14-e17f-4836-8403-fe4a4ab247d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UnitApproval[nominal_maksimal]</value>
      <webElementGuid>f1450aca-f957-4d09-bba7-4638abf64120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5000000</value>
      <webElementGuid>2cdd996a-e0a6-4139-b795-8f84cca050c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unitapproval-nominal_maksimal&quot;)</value>
      <webElementGuid>87958c08-7e31-46b1-8da0-93a9b47edaa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unitapproval-nominal_maksimal']</value>
      <webElementGuid>f8c20557-5223-40d0-bad2-4f45ea137514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[4]/input</value>
      <webElementGuid>120e73e0-ec2c-4684-b4f0-a49a5f5edbf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>07c05eda-2107-4a4b-8e03-268d8ff01e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'unitapproval-nominal_maksimal' and @name = 'UnitApproval[nominal_maksimal]']</value>
      <webElementGuid>c0c6091a-c697-40a7-8b7b-c23ff5f79af2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
