<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Lahir_Mustahiktanggal_lahir</name>
   <tag></tag>
   <elementGuidId>7a875be7-1e1e-4f08-8ff2-30eafe4a90fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mustahik-tanggal_lahir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mustahik-tanggal_lahir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41faf53b-7fa6-4718-a8c3-4148bebd93a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ff2d750-d08a-4a8a-b746-b7fb1e0ec256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-tanggal_lahir</value>
      <webElementGuid>213108da-b6b0-47ec-aead-21655028b65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control krajee-datepicker</value>
      <webElementGuid>07143a37-6e10-4f90-9884-c8c4844c4942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[tanggal_lahir]</value>
      <webElementGuid>050d2fcd-0939-4499-8a8c-7cf748d30a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>9d6ca686-c668-4a5b-92cb-5c49a174a13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datepicker-source</name>
      <type>Main</type>
      <value>mustahik-tanggal_lahir</value>
      <webElementGuid>aeda2218-3324-43cd-b477-d669fe953491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datepicker-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>96928bb3-bc1a-4bcb-873a-232cc8d8835a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-krajee-kvdatepicker</name>
      <type>Main</type>
      <value>kvDatepicker_cb1a2551</value>
      <webElementGuid>7a2c49aa-672e-4474-8580-9c3ef58f0488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-tanggal_lahir&quot;)</value>
      <webElementGuid>8dfea520-0bd2-463d-a442-f28656ccd232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mustahik-tanggal_lahir']</value>
      <webElementGuid>6c1b59f5-f4ad-4437-9a3d-eb814ec6c476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div/div[4]/input</value>
      <webElementGuid>ebcbc16e-fb8d-4ec0-870d-5d0cba7796df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>2765805a-2041-4434-8f83-e653f1bb58a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mustahik-tanggal_lahir' and @name = 'Mustahik[tanggal_lahir]' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>29a31fa1-1432-4e8c-9047-81ff65b375ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
