<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No HP_BantuanMustahikmustahik_id (2)</name>
   <tag></tag>
   <elementGuidId>a19d36c3-e398-4335-ae2c-16979b86ce6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuanmustahik-mustahik_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuanmustahik-mustahik_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60b4601f-ddb6-4ccf-959e-e4627a9bcdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c7b215df-adc1-4428-9e71-237ffa862b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuanmustahik-mustahik_id</value>
      <webElementGuid>e51837e3-9fec-4675-9028-691604e37d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BantuanMustahik[mustahik_id][]</value>
      <webElementGuid>450a12b6-84c6-42d4-85e5-2095690129bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>c962205a-0d45-489f-a2f5-7a0258074059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>options</name>
      <type>Main</type>
      <value>{&quot;class&quot;:&quot;checkbox-row&quot;}</value>
      <webElementGuid>01835aa0-bc2e-4647-961b-652f4ecc5d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w0&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-hover&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;form-group field-bantuanmustahik-mustahik_id&quot;]/input[@id=&quot;bantuanmustahik-mustahik_id&quot;]</value>
      <webElementGuid>fc22db9e-0ef9-43b6-a5b8-55db2e5c907d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuanmustahik-mustahik_id']</value>
      <webElementGuid>16f77509-e77a-43f1-bb5c-0ac864f998ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/div/div[2]/div/table/tbody/tr/td/div/input[2]</value>
      <webElementGuid>a7b21fa5-1491-4730-adc6-d7cc42a2963b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>cb7df492-d124-414d-b064-e75c82494c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'bantuanmustahik-mustahik_id' and @name = 'BantuanMustahik[mustahik_id][]']</value>
      <webElementGuid>fec1e118-35ab-4349-9ac4-c825b84941a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
