<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NO KK_Mustahikno_kk</name>
   <tag></tag>
   <elementGuidId>9788957d-80a5-41cc-aca0-7c532f31c8a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mustahik-no_kk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mustahik-no_kk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11cad1b3-3f19-4830-991f-a8c2be0da6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8608667b-854e-438a-bfd7-c6342492a53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-no_kk</value>
      <webElementGuid>0b7ae31e-e168-4f14-beee-abfda7a5fdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>988ea75b-9bc6-45a8-b920-9e9a107f1f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[no_kk]</value>
      <webElementGuid>c937bf8e-e3a9-416b-91fc-64d14af30a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-no_kk&quot;)</value>
      <webElementGuid>b4deb897-ba22-4165-9c49-55e310174e23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mustahik-no_kk']</value>
      <webElementGuid>6c1aa2a1-6ed7-41d3-a42c-f65caab6b83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div/div[5]/input</value>
      <webElementGuid>a55dd157-3d5c-4d93-81c4-24844dce8514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>53b4c2a2-6660-4fe6-90d8-08d3d89b6a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mustahik-no_kk' and @name = 'Mustahik[no_kk]']</value>
      <webElementGuid>234f2edd-6b8c-4f32-b90e-bd39552532f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
