<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No HP_BantuanMustahikmustahik_id</name>
   <tag></tag>
   <elementGuidId>45b2bff9-c539-49fe-8ce2-6f5d433fa92a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuanmustahik-mustahik_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuanmustahik-mustahik_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85192bb3-7cfc-4f68-b337-01a85796e055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4999c847-822d-4464-8de1-c78bfb281c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuanmustahik-mustahik_id</value>
      <webElementGuid>858eb38c-e899-49e0-90a5-342b9c0ce860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BantuanMustahik[mustahik_id][]</value>
      <webElementGuid>e2516b09-843c-439e-9956-df053cccea9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>74bac746-d684-46a5-b147-bf250290cc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>options</name>
      <type>Main</type>
      <value>{&quot;class&quot;:&quot;checkbox-row&quot;}</value>
      <webElementGuid>c38c6af0-8ba0-420a-8249-0b0ea8575647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w0&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-hover&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;form-group field-bantuanmustahik-mustahik_id&quot;]/input[@id=&quot;bantuanmustahik-mustahik_id&quot;]</value>
      <webElementGuid>201ce4c0-11bc-4ca3-b1b0-a19711840ff9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuanmustahik-mustahik_id']</value>
      <webElementGuid>a3aeb862-9609-4a64-ac24-eec33ce8a84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/div/div[2]/div/table/tbody/tr/td/div/input[2]</value>
      <webElementGuid>9310cae2-e54c-4f24-9545-a122951ec832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>abf9e400-9c9a-43d0-995f-ece48a2fa9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'bantuanmustahik-mustahik_id' and @name = 'BantuanMustahik[mustahik_id][]']</value>
      <webElementGuid>a4995171-5a70-4898-849e-b011aa24417d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
