<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No HP_BantuanMustahikmustahik_id (1)</name>
   <tag></tag>
   <elementGuidId>3bf8d66d-01c3-4276-a7a6-da262e69072c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bantuanmustahik-mustahik_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bantuanmustahik-mustahik_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87befe61-26b7-4daa-8170-0f4c4e1b1f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>db3bd635-c235-4285-8ded-7361987d4f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bantuanmustahik-mustahik_id</value>
      <webElementGuid>b822075a-f781-405a-9a31-b8488e32721a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BantuanMustahik[mustahik_id][]</value>
      <webElementGuid>57726a28-32ce-41ec-a23d-2677237e1c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>e44902b9-1bbe-4325-9c8d-c240fd77362f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>options</name>
      <type>Main</type>
      <value>{&quot;class&quot;:&quot;checkbox-row&quot;}</value>
      <webElementGuid>1df0919a-25c5-4a8c-95c7-16d4f95e7c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w0&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-hover&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;form-group field-bantuanmustahik-mustahik_id&quot;]/input[@id=&quot;bantuanmustahik-mustahik_id&quot;]</value>
      <webElementGuid>d6cb0744-b2c3-412f-be54-774d511d4f7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bantuanmustahik-mustahik_id']</value>
      <webElementGuid>42e7cdb5-5d37-4cbc-b4c0-e7b97d238ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/div/div[2]/div/table/tbody/tr/td/div/input[2]</value>
      <webElementGuid>58d8cc98-3074-4a89-ad2c-d597100ada96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>57f94ac5-b544-44e3-b323-ec4069f520f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'bantuanmustahik-mustahik_id' and @name = 'BantuanMustahik[mustahik_id][]']</value>
      <webElementGuid>6065535a-6df1-4d34-ad30-f1b282a4d105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
