<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Daftar_Mustahiktanggal_daftar</name>
   <tag></tag>
   <elementGuidId>2faddd90-4e26-42a2-a3f3-d53394335ab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mustahik-tanggal_daftar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mustahik-tanggal_daftar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a8c4ff9-d234-48a6-b49c-a4557bddc7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b3c103e-0d9d-48a4-b47e-99d534e6d3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-tanggal_daftar</value>
      <webElementGuid>3d36bf1d-e8e3-4c66-9b84-8b8bb2323808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control krajee-datepicker</value>
      <webElementGuid>71856983-7b3e-413c-b853-0409989e9145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[tanggal_daftar]</value>
      <webElementGuid>9a31b280-f6f7-41f5-8244-090b5ac6a549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>536b64a1-d1c8-4440-8ad6-25da87ffcc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datepicker-source</name>
      <type>Main</type>
      <value>mustahik-tanggal_daftar</value>
      <webElementGuid>825b6c4a-da7e-4408-aa0c-02117f22bcc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datepicker-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e3d4e61c-1731-4991-908c-9a12632e9df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-krajee-kvdatepicker</name>
      <type>Main</type>
      <value>kvDatepicker_4e024ef8</value>
      <webElementGuid>24584060-d338-4ad0-a33d-8c91d59ba7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-tanggal_daftar&quot;)</value>
      <webElementGuid>0e79ff61-69da-46d3-9e95-6b5cf5aade9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mustahik-tanggal_daftar']</value>
      <webElementGuid>e1499b79-9257-4407-abb9-ad3558679681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div/div[10]/input</value>
      <webElementGuid>9775dd39-82b4-431c-a960-bbca89361988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>157f86fe-90a1-4311-a836-48b8bcbc2887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mustahik-tanggal_daftar' and @name = 'Mustahik[tanggal_daftar]' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>f7acae3d-74a7-4f52-9632-97726afd984d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
