<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih KabupatenKota --KABUPATEN B_d49847</name>
   <tag></tag>
   <elementGuidId>26981c62-27c5-4c0c-8e80-daca07b9cf40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='mustahik-kota_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mustahik-kota_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>60eacc64-88b7-4f9d-a449-45a6653427ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-kota_id</value>
      <webElementGuid>59ce16fb-8c64-49ce-b636-eb4076fe1005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>09d80acc-a360-4558-b9b9-c49d94d4d4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[kota_id]</value>
      <webElementGuid>d01fdeb8-a40e-4d80-b507-889d3bed5b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>
                                                    $.get( &quot;/backend/web/index.php?r=mustahik%2Flist-kecamatan&quot;, { param: $(this).val() } )
                                                        .done(function( data ) {
                                                            $( &quot;#mustahik-kecamatan_id&quot; ).html( data );
                                                        }
                                                    );
                                                    </value>
      <webElementGuid>c8029c44-c973-499a-9c36-b1ccd5304b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kabupaten/Kota --KABUPATEN BANGKALANKABUPATEN BANYUWANGIKABUPATEN BLITARKABUPATEN BOJONEGOROKABUPATEN BONDOWOSOKABUPATEN GRESIKKABUPATEN JEMBERKABUPATEN JOMBANGKABUPATEN KEDIRIKABUPATEN LAMONGANKABUPATEN LUMAJANGKABUPATEN MADIUNKABUPATEN MAGETANKABUPATEN MALANGKABUPATEN MOJOKERTOKABUPATEN NGANJUKKABUPATEN NGAWIKABUPATEN PACITANKABUPATEN PAMEKASANKABUPATEN PASURUANKABUPATEN PONOROGOKABUPATEN PROBOLINGGOKABUPATEN SAMPANGKABUPATEN SIDOARJOKABUPATEN SITUBONDOKABUPATEN SUMENEPKABUPATEN TRENGGALEKKABUPATEN TUBANKABUPATEN TULUNGAGUNGKOTA BATUKOTA BLITARKOTA KEDIRIKOTA MADIUNKOTA MALANGKOTA MOJOKERTOKOTA PASURUANKOTA PROBOLINGGOKOTA SURABAYA</value>
      <webElementGuid>30b520bb-3275-49b0-bef7-6034ece85439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-kota_id&quot;)</value>
      <webElementGuid>e96e2bc2-ac79-4e97-abc2-426e342c8914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='mustahik-kota_id']</value>
      <webElementGuid>550a6ab2-eeec-458f-a35c-17bfa73f1d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div[2]/div/div[2]/div/div[2]/div/select</value>
      <webElementGuid>b72b8ef9-1329-403a-a44c-a8c37f724517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota / Kabupaten'])[1]/following::select[1]</value>
      <webElementGuid>e9649727-d2e8-4378-a066-b3b851ca0853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi'])[1]/following::select[2]</value>
      <webElementGuid>ea79278b-68d4-4def-8df8-acb7d24bc069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/preceding::select[1]</value>
      <webElementGuid>59e75d71-ffb3-4043-b618-3a8444f6f692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan / Desa'])[1]/preceding::select[2]</value>
      <webElementGuid>9874cf4a-a990-4fab-838b-4c47c997dd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>9092ee59-a06a-4626-9506-a3ea586a0a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'mustahik-kota_id' and @name = 'Mustahik[kota_id]' and (text() = '-- Pilih Kabupaten/Kota --KABUPATEN BANGKALANKABUPATEN BANYUWANGIKABUPATEN BLITARKABUPATEN BOJONEGOROKABUPATEN BONDOWOSOKABUPATEN GRESIKKABUPATEN JEMBERKABUPATEN JOMBANGKABUPATEN KEDIRIKABUPATEN LAMONGANKABUPATEN LUMAJANGKABUPATEN MADIUNKABUPATEN MAGETANKABUPATEN MALANGKABUPATEN MOJOKERTOKABUPATEN NGANJUKKABUPATEN NGAWIKABUPATEN PACITANKABUPATEN PAMEKASANKABUPATEN PASURUANKABUPATEN PONOROGOKABUPATEN PROBOLINGGOKABUPATEN SAMPANGKABUPATEN SIDOARJOKABUPATEN SITUBONDOKABUPATEN SUMENEPKABUPATEN TRENGGALEKKABUPATEN TUBANKABUPATEN TULUNGAGUNGKOTA BATUKOTA BLITARKOTA KEDIRIKOTA MADIUNKOTA MALANGKOTA MOJOKERTOKOTA PASURUANKOTA PROBOLINGGOKOTA SURABAYA' or . = '-- Pilih Kabupaten/Kota --KABUPATEN BANGKALANKABUPATEN BANYUWANGIKABUPATEN BLITARKABUPATEN BOJONEGOROKABUPATEN BONDOWOSOKABUPATEN GRESIKKABUPATEN JEMBERKABUPATEN JOMBANGKABUPATEN KEDIRIKABUPATEN LAMONGANKABUPATEN LUMAJANGKABUPATEN MADIUNKABUPATEN MAGETANKABUPATEN MALANGKABUPATEN MOJOKERTOKABUPATEN NGANJUKKABUPATEN NGAWIKABUPATEN PACITANKABUPATEN PAMEKASANKABUPATEN PASURUANKABUPATEN PONOROGOKABUPATEN PROBOLINGGOKABUPATEN SAMPANGKABUPATEN SIDOARJOKABUPATEN SITUBONDOKABUPATEN SUMENEPKABUPATEN TRENGGALEKKABUPATEN TUBANKABUPATEN TULUNGAGUNGKOTA BATUKOTA BLITARKOTA KEDIRIKOTA MADIUNKOTA MALANGKOTA MOJOKERTOKOTA PASURUANKOTA PROBOLINGGOKOTA SURABAYA')]</value>
      <webElementGuid>c1208b92-cc65-400e-bfab-fb5dbcad4e05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
