<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih Kecamatan --BANDAR KEDUNG M_70a2e7</name>
   <tag></tag>
   <elementGuidId>2adfbd22-3f0d-4e14-aff2-2e7929a1d6a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='mustahik-kecamatan_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mustahik-kecamatan_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d7b952fc-891c-4fff-931d-dedae62a2f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-kecamatan_id</value>
      <webElementGuid>30be7300-95ae-4c7e-ac39-d16850f99724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>402c5b18-c613-4095-ac5c-84547adecc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[kecamatan_id]</value>
      <webElementGuid>2ed25446-ec59-47d0-9ade-1957e932a409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>
                                                    $.get( &quot;/backend/web/index.php?r=mustahik%2Flist-desa&quot;, { param: $(this).val() } )
                                                        .done(function( data ) {
                                                            $( &quot;#mustahik-desa_id&quot; ).html( data );
                                                        }
                                                    );
                                                    </value>
      <webElementGuid>992d46af-7ffe-4541-8920-d18d566cc11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kecamatan --BANDAR KEDUNG MULYOBARENGDIWEKGUDOJOGO ROTOJOMBANGKABUHKESAMBENKUDUMEGALUHMOJOAGUNGMOJOWARNONGORONGUSIKANPERAKPETERONGANPLANDAANPLOSOSUMOBITOTEMBELANGWONOSALAM</value>
      <webElementGuid>6a124d43-c3dd-481b-bd3f-8b46ed50f16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-kecamatan_id&quot;)</value>
      <webElementGuid>d039f150-c9e7-4be0-8ea8-19e43b2e2a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='mustahik-kecamatan_id']</value>
      <webElementGuid>c6310243-bc82-46ee-bd75-82e6c9b9e2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div[2]/div/div[2]/div/div[3]/div/select</value>
      <webElementGuid>4c9b1c16-959a-43e0-9d57-3d08f30daeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/following::select[1]</value>
      <webElementGuid>661c7a92-a578-4fb5-b85c-3595381f9ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota / Kabupaten'])[1]/following::select[2]</value>
      <webElementGuid>7a14f4b2-9d36-45ea-85be-d03efb4d69ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan / Desa'])[1]/preceding::select[1]</value>
      <webElementGuid>35edd089-2e40-42b6-8f38-83eaa5ced1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Rumah'])[1]/preceding::select[2]</value>
      <webElementGuid>79bd5307-9baf-473b-9625-2cebb35ed284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>56ace3b0-deba-428f-9192-08efa1f4f2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'mustahik-kecamatan_id' and @name = 'Mustahik[kecamatan_id]' and (text() = '-- Pilih Kecamatan --BANDAR KEDUNG MULYOBARENGDIWEKGUDOJOGO ROTOJOMBANGKABUHKESAMBENKUDUMEGALUHMOJOAGUNGMOJOWARNONGORONGUSIKANPERAKPETERONGANPLANDAANPLOSOSUMOBITOTEMBELANGWONOSALAM' or . = '-- Pilih Kecamatan --BANDAR KEDUNG MULYOBARENGDIWEKGUDOJOGO ROTOJOMBANGKABUHKESAMBENKUDUMEGALUHMOJOAGUNGMOJOWARNONGORONGUSIKANPERAKPETERONGANPLANDAANPLOSOSUMOBITOTEMBELANGWONOSALAM')]</value>
      <webElementGuid>0fd0e804-bb4a-428a-8770-21599ac1b17b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
