<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih KelurahanDesa --BALONG BESU_b58b8d</name>
   <tag></tag>
   <elementGuidId>a6b4eff1-6cbe-4be0-a6e8-496f251bc16e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='mustahik-desa_domisili']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mustahik-desa_domisili</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7542107b-ed2b-43b8-ade9-f799b95e25ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-desa_domisili</value>
      <webElementGuid>6452a758-9bc9-4e4f-98c2-9493c737947b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b999204d-7e3f-48d3-a74a-b69715464714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[desa_domisili]</value>
      <webElementGuid>2922847c-ffbc-4796-87d7-3b4d0add567c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kelurahan/Desa --BALONG BESUKBANDUNGBRAMBANGBULUREJOCUKIRDIWEKGROGOLJATIPELEMJATIREJOKAYANGANKEDAWONGKERASKWARONNGUDIREJOPANDANWANGIPUNDONGPUTONWATUGALUH</value>
      <webElementGuid>de652b07-e8c0-4e9d-83ff-2acfc848de8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-desa_domisili&quot;)</value>
      <webElementGuid>f3300540-ff37-431e-ab8a-97f7276c6a28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='mustahik-desa_domisili']</value>
      <webElementGuid>c485e122-5332-4e89-87c2-09805f761719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div[2]/div[2]/div[2]/div[2]/div[4]/div/select</value>
      <webElementGuid>5336fa72-9229-4d18-9be0-6d4a468ae291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan / Desa'])[2]/following::select[1]</value>
      <webElementGuid>89aa6d53-8496-4c23-9770-ed3c9004dbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[2]/following::select[2]</value>
      <webElementGuid>eccc1dc9-b149-4d4c-8e1b-34dd8ea72cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Domisili'])[2]/preceding::select[1]</value>
      <webElementGuid>32f6b99e-c092-4988-92ca-fb7a398c599b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maps Domisili'])[1]/preceding::select[1]</value>
      <webElementGuid>37fd0f18-770a-4436-80cb-19335d6559fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/select</value>
      <webElementGuid>ec713a91-9503-4c8a-ae82-74248d79104f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'mustahik-desa_domisili' and @name = 'Mustahik[desa_domisili]' and (text() = '-- Pilih Kelurahan/Desa --BALONG BESUKBANDUNGBRAMBANGBULUREJOCUKIRDIWEKGROGOLJATIPELEMJATIREJOKAYANGANKEDAWONGKERASKWARONNGUDIREJOPANDANWANGIPUNDONGPUTONWATUGALUH' or . = '-- Pilih Kelurahan/Desa --BALONG BESUKBANDUNGBRAMBANGBULUREJOCUKIRDIWEKGROGOLJATIPELEMJATIREJOKAYANGANKEDAWONGKERASKWARONNGUDIREJOPANDANWANGIPUNDONGPUTONWATUGALUH')]</value>
      <webElementGuid>e36b1a06-baa1-48c0-9a59-b3d5c557e0ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
