<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih KelurahanDesa --BADASBAKALA_243d93</name>
   <tag></tag>
   <elementGuidId>90769c3f-47c7-4561-babb-b7e49dc8721e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='mustahik-desa_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mustahik-desa_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b722e2aa-6efe-4fcf-9c3c-565a52e3da54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-desa_id</value>
      <webElementGuid>523a7823-c5c0-47b4-91fb-b6bc3558a1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d1f6ee4e-641d-40e5-b31b-60b0e4281829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[desa_id]</value>
      <webElementGuid>5be375b3-237c-4a45-8831-5a7d2def0077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kelurahan/Desa --BADASBAKALANBUDUGSIDOREJOCURAH MALANGGEDANGANJOGOLOYOKEDUNGPAPARKENDALSARIMADYO PUROMENTOROMLARASPALREJOPLEMAHANPLOSOKEREPSEBANISEGODOREJOSUMOBITOTALUN KIDULTRAWASAN</value>
      <webElementGuid>8b3303ed-3d54-43a5-aa8a-3e3a2c55cd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-desa_id&quot;)</value>
      <webElementGuid>25fa6b3a-fd9a-45c7-a703-2fc5ded9a088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='mustahik-desa_id']</value>
      <webElementGuid>83cd74dc-c428-4e2f-a2ca-0253392b49b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div[2]/div/div[2]/div/div[4]/div/select</value>
      <webElementGuid>1d2221d2-1ecc-4a65-973f-364a30a9f6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan / Desa'])[1]/following::select[1]</value>
      <webElementGuid>ef0ecce4-5bd0-4397-8d0b-5d7c424a0fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/following::select[2]</value>
      <webElementGuid>6d3bbe54-2f27-4efd-a0cd-55b7779b2b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Rumah'])[1]/preceding::select[1]</value>
      <webElementGuid>af3eb9e7-4d42-49cd-a5ae-32528228d757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Domisili'])[1]/preceding::select[1]</value>
      <webElementGuid>97c634e5-6be9-4f9b-9719-2b978c93ff64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>be90e4e1-8e54-4b02-9e39-81fe2b26329d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'mustahik-desa_id' and @name = 'Mustahik[desa_id]' and (text() = '-- Pilih Kelurahan/Desa --BADASBAKALANBUDUGSIDOREJOCURAH MALANGGEDANGANJOGOLOYOKEDUNGPAPARKENDALSARIMADYO PUROMENTOROMLARASPALREJOPLEMAHANPLOSOKEREPSEBANISEGODOREJOSUMOBITOTALUN KIDULTRAWASAN' or . = '-- Pilih Kelurahan/Desa --BADASBAKALANBUDUGSIDOREJOCURAH MALANGGEDANGANJOGOLOYOKEDUNGPAPARKENDALSARIMADYO PUROMENTOROMLARASPALREJOPLEMAHANPLOSOKEREPSEBANISEGODOREJOSUMOBITOTALUN KIDULTRAWASAN')]</value>
      <webElementGuid>e9c2fb3c-3679-44d2-ba65-a1299d0b74b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
