<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat Domisili_Mustahikalamat_domisili</name>
   <tag></tag>
   <elementGuidId>e19a512f-97d3-4e28-b0d6-09009ffd5047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='mustahik-alamat_domisili']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mustahik-alamat_domisili</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1dadf04a-7377-4d0d-9dc5-04f21c969a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-alamat_domisili</value>
      <webElementGuid>12c5ec0a-7702-4b32-8aff-abb6ec4daa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2a55a974-92d8-49cb-8bd3-60171f7f1699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[alamat_domisili]</value>
      <webElementGuid>d5501069-9779-42f4-938e-cd864bcdff8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9ad15bd3-3c2d-4106-8e83-8e187a70979e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-alamat_domisili&quot;)</value>
      <webElementGuid>a148187d-6875-4bf9-ac82-edc34a56d8d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='mustahik-alamat_domisili']</value>
      <webElementGuid>07b62082-7323-490d-8a45-5176330aa3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div[2]/div[2]/div[2]/div[3]/textarea</value>
      <webElementGuid>e15eab31-7369-4af1-9642-fe195a6d4de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>cd51cc7c-e10a-4f5c-83d8-8d9d182b0c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'mustahik-alamat_domisili' and @name = 'Mustahik[alamat_domisili]']</value>
      <webElementGuid>9f1ebd4c-f74b-433d-bb5f-92eb381b951a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
