<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Atas Nama_Lembagabank_nama_pemilik</name>
   <tag></tag>
   <elementGuidId>c3ad6311-cd92-4e92-a5e0-bc0cc778af60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lembaga-bank_nama_pemilik']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lembaga-bank_nama_pemilik</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bcf3e06-4892-4e46-b938-ee4c1fc8b08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8ba055e-30c3-459d-b9c2-485f57561115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lembaga-bank_nama_pemilik</value>
      <webElementGuid>53a11776-a5ca-41f9-a641-a4124791ece8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8bac7b5f-ca29-4169-bb26-c3b98c4399cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Lembaga[bank_nama_pemilik]</value>
      <webElementGuid>49fe8095-9ef0-4257-bc06-d30fc5844261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>2a257466-2efd-4505-a6a6-afd06d3695c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lembaga-bank_nama_pemilik&quot;)</value>
      <webElementGuid>c10483d1-0e1a-41d4-89ac-b141753e629c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lembaga-bank_nama_pemilik']</value>
      <webElementGuid>eb2d10f2-938b-4613-93c7-368fe74252e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div[2]/div[6]/div[2]/div/input</value>
      <webElementGuid>d73ed440-1436-4231-afa7-c1e9dc770d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/input</value>
      <webElementGuid>d12c70bb-cb51-4240-a113-e884e8566105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lembaga-bank_nama_pemilik' and @name = 'Lembaga[bank_nama_pemilik]']</value>
      <webElementGuid>eaa1823c-aafa-4369-b119-a789539d2a92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
