<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_Lembagatelepon_pj</name>
   <tag></tag>
   <elementGuidId>13f9cb7d-ff45-4622-832a-97c6b573c57c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lembaga-telepon_pj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lembaga-telepon_pj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5a65535-81b5-413d-8dd7-15a9de3cccf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e704c90f-cc9b-4f5d-ba0a-0371c7fd3eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lembaga-telepon_pj</value>
      <webElementGuid>3e829fc5-c7bd-4f97-8877-8d3714a6794e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fa3cc994-c2ba-4ee2-a361-98b47990e5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Lembaga[telepon_pj]</value>
      <webElementGuid>ad57d6f1-97ad-4297-80e6-3a282c0173c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>5af90f67-a72c-4a3c-807c-61f22276d334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lembaga-telepon_pj&quot;)</value>
      <webElementGuid>4bfd883b-cf06-42ac-8cc4-14993cb9b5fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lembaga-telepon_pj']</value>
      <webElementGuid>623c4d3a-878a-4bdc-870c-b566ee55d069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div[2]/div[4]/div[2]/div/input</value>
      <webElementGuid>afb8097e-36dc-493c-8b0e-c42ca4f3ef34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>ee4b1039-33d0-4fb6-b578-c0785160d021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lembaga-telepon_pj' and @name = 'Lembaga[telepon_pj]']</value>
      <webElementGuid>5c0aabc3-e08f-4bd4-97d1-e4b566d1a323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
