<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih KelurahanDesa --BANJAR DOWO_08a6d5 (1)</name>
   <tag></tag>
   <elementGuidId>39565440-0394-44e6-9798-25769502178f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='lembaga-desa_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lembaga-desa_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>365fda4b-e86d-4aec-b70e-d3af1ca857e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lembaga-desa_id</value>
      <webElementGuid>a2555b90-7c8c-48c5-bcf2-ec9d791f6e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1e58d721-6b9f-4e59-afbb-deea18475800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Lembaga[desa_id]</value>
      <webElementGuid>829d462c-5a43-4034-b224-3be0295f22d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kelurahan/Desa --BANJAR DOWOCANDI MULYODAPUR KEJAMBONDENANYARJABONJELAKOMBOJOMBANGJOMBATANKALIWUNGUKEPANJENKEPATIHANMOJONGAPITPLANDIPLOSOGENENGPULO LORSAMBONG DUKUHSENGONSUMBERJOTAMBAK REJOTUNGGORONO</value>
      <webElementGuid>738d0f83-5d22-400d-bed2-19577d19d536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lembaga-desa_id&quot;)</value>
      <webElementGuid>a2a36917-b2e9-473f-aafb-4e00a134fbc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='lembaga-desa_id']</value>
      <webElementGuid>65d50d6c-3dc0-4b08-ab99-34b1e29cda98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div/div[9]/div[2]/div/select</value>
      <webElementGuid>81102f00-7e87-4935-96b1-442f0eaf6962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa'])[1]/following::select[1]</value>
      <webElementGuid>518e3681-911c-47c5-a7ce-cf98f81257e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/following::select[2]</value>
      <webElementGuid>ca85c6ca-5e6e-4863-8d42-004302b3a4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Lengkap'])[1]/preceding::select[1]</value>
      <webElementGuid>97675215-4437-4f0b-8996-b32abba24e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Penanggung Jawab'])[1]/preceding::select[1]</value>
      <webElementGuid>f9334304-23f7-4236-bf13-237bac4f5d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/select</value>
      <webElementGuid>9c6e30e9-4948-4d3b-b82f-fe2adbd4ce2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'lembaga-desa_id' and @name = 'Lembaga[desa_id]' and (text() = '-- Pilih Kelurahan/Desa --BANJAR DOWOCANDI MULYODAPUR KEJAMBONDENANYARJABONJELAKOMBOJOMBANGJOMBATANKALIWUNGUKEPANJENKEPATIHANMOJONGAPITPLANDIPLOSOGENENGPULO LORSAMBONG DUKUHSENGONSUMBERJOTAMBAK REJOTUNGGORONO' or . = '-- Pilih Kelurahan/Desa --BANJAR DOWOCANDI MULYODAPUR KEJAMBONDENANYARJABONJELAKOMBOJOMBANGJOMBATANKALIWUNGUKEPANJENKEPATIHANMOJONGAPITPLANDIPLOSOGENENGPULO LORSAMBONG DUKUHSENGONSUMBERJOTAMBAK REJOTUNGGORONO')]</value>
      <webElementGuid>b6a80f31-e1b7-4e31-9988-dae124e238e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
