<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih KelurahanDesa --BANJAR DOWO_08a6d5</name>
   <tag></tag>
   <elementGuidId>b5e182d4-cd6d-442e-84a4-61532aa5841a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='lembaga-desa_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lembaga-desa_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lembaga-desa_id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d53d29d9-b93b-43c9-ad64-23442ae8aec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lembaga-desa_id</value>
      <webElementGuid>ca131070-a008-4fc8-8b41-2fb375a7d61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6e63ab65-49b3-4b25-9b0a-5850cfd640a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Lembaga[desa_id]</value>
      <webElementGuid>6fc1ae15-4932-440a-93be-2cf267b5588e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kelurahan/Desa --BANJAR DOWOCANDI MULYODAPUR KEJAMBONDENANYARJABONJELAKOMBOJOMBANGJOMBATANKALIWUNGUKEPANJENKEPATIHANMOJONGAPITPLANDIPLOSOGENENGPULO LORSAMBONG DUKUHSENGONSUMBERJOTAMBAK REJOTUNGGORONO</value>
      <webElementGuid>fc5ecc2c-1701-4cf4-9c44-a5d594e6f1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lembaga-desa_id&quot;)</value>
      <webElementGuid>04a1635b-6e3a-4756-9047-da0c37951c90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='lembaga-desa_id']</value>
      <webElementGuid>316ada27-31fb-49a8-a709-7161dc5190fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div/div[9]/div[2]/div/select</value>
      <webElementGuid>fa753444-e3a9-4eb4-8e80-a62cc75e8a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa'])[1]/following::select[1]</value>
      <webElementGuid>a3f7fdfc-309a-427d-8c7d-84930cc7fcb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/following::select[2]</value>
      <webElementGuid>068902dd-b638-4274-8bdc-7e2f06719092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Lengkap'])[1]/preceding::select[1]</value>
      <webElementGuid>ab0b937a-9fe5-4c4f-98ab-fc0db9168354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Penanggung Jawab'])[1]/preceding::select[1]</value>
      <webElementGuid>c212ce1c-b98c-45af-8da7-e5e6eb48b211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/select</value>
      <webElementGuid>b509cbf3-1d77-4734-84ca-2d4d248a8635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'lembaga-desa_id' and @name = 'Lembaga[desa_id]' and (text() = '-- Pilih Kelurahan/Desa --BANJAR DOWOCANDI MULYODAPUR KEJAMBONDENANYARJABONJELAKOMBOJOMBANGJOMBATANKALIWUNGUKEPANJENKEPATIHANMOJONGAPITPLANDIPLOSOGENENGPULO LORSAMBONG DUKUHSENGONSUMBERJOTAMBAK REJOTUNGGORONO' or . = '-- Pilih Kelurahan/Desa --BANJAR DOWOCANDI MULYODAPUR KEJAMBONDENANYARJABONJELAKOMBOJOMBANGJOMBATANKALIWUNGUKEPANJENKEPATIHANMOJONGAPITPLANDIPLOSOGENENGPULO LORSAMBONG DUKUHSENGONSUMBERJOTAMBAK REJOTUNGGORONO')]</value>
      <webElementGuid>20feea6c-a00c-4ca0-ba90-6256735839b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
