<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih Kecamatan --BANDAR KEDUNG M_70a2e7</name>
   <tag></tag>
   <elementGuidId>92e88e25-6dde-473c-a77b-56aa87848f8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='lembaga-kecamatan_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lembaga-kecamatan_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2f60d8c8-8927-40fd-8f74-4f2f70eb6b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lembaga-kecamatan_id</value>
      <webElementGuid>aafdc09d-99bd-420a-9e19-f2efb316b270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1f1bba80-ecfa-4a3d-94e2-41805715f69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Lembaga[kecamatan_id]</value>
      <webElementGuid>3d4ba25e-e662-4274-bd8c-7ea31ec6b488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>
                                $.get( &quot;/backend/web/index.php?r=mustahik%2Flist-desa&quot;, { param: $(this).val() } )
                                    .done(function( data ) {
                                        $( &quot;#lembaga-desa_id&quot; ).html( data );
                                    }
                                );
                                </value>
      <webElementGuid>842d45ef-5b95-4a79-9726-e73eaa233c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kecamatan --BANDAR KEDUNG MULYOBARENGDIWEKGUDOJOGO ROTOJOMBANGKABUHKESAMBENKUDUMEGALUHMOJOAGUNGMOJOWARNONGORONGUSIKANPERAKPETERONGANPLANDAANPLOSOSUMOBITOTEMBELANGWONOSALAM</value>
      <webElementGuid>dd3d6767-e726-42b0-afa6-89b2af8f155b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lembaga-kecamatan_id&quot;)</value>
      <webElementGuid>08a85fd6-3de0-488f-9496-2d58666eed31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='lembaga-kecamatan_id']</value>
      <webElementGuid>9c0d2370-ee18-40b7-aa76-c1156aeafe2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div/div[8]/div[2]/div/select</value>
      <webElementGuid>4ca9ce6b-ab0f-42a4-8cdf-6d708956786f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/following::select[1]</value>
      <webElementGuid>74262917-1e68-461b-896f-e8d4994ded75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota'])[1]/following::select[2]</value>
      <webElementGuid>a3eb0783-8eed-47e5-b69b-d96d2c0aae6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa'])[1]/preceding::select[1]</value>
      <webElementGuid>ab59402d-58a9-4af2-bf1f-67954f96268d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Lengkap'])[1]/preceding::select[2]</value>
      <webElementGuid>8ba15cdb-9846-43c1-b84a-1fbbc40f50d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/select</value>
      <webElementGuid>66964217-d394-420d-b8c0-33c514b68fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'lembaga-kecamatan_id' and @name = 'Lembaga[kecamatan_id]' and (text() = '-- Pilih Kecamatan --BANDAR KEDUNG MULYOBARENGDIWEKGUDOJOGO ROTOJOMBANGKABUHKESAMBENKUDUMEGALUHMOJOAGUNGMOJOWARNONGORONGUSIKANPERAKPETERONGANPLANDAANPLOSOSUMOBITOTEMBELANGWONOSALAM' or . = '-- Pilih Kecamatan --BANDAR KEDUNG MULYOBARENGDIWEKGUDOJOGO ROTOJOMBANGKABUHKESAMBENKUDUMEGALUHMOJOAGUNGMOJOWARNONGORONGUSIKANPERAKPETERONGANPLANDAANPLOSOSUMOBITOTEMBELANGWONOSALAM')]</value>
      <webElementGuid>2ee7edd9-3bd8-49f0-af07-ec49e308d07a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
