<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat Lengkap_Lembagaalamat (1)</name>
   <tag></tag>
   <elementGuidId>f7e53212-bc67-4deb-8fa8-ed0c52ac8ab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='lembaga-alamat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lembaga-alamat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>34518e9a-c39d-46d6-984c-2bc9ed3be97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lembaga-alamat</value>
      <webElementGuid>63972243-75bf-4179-9c0d-610893c50fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cfc20ba3-12f9-481a-8e71-288855ba08ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Lembaga[alamat]</value>
      <webElementGuid>663bb1b1-9606-4222-a74c-c1f54098c22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1183705c-6127-4077-8866-e2f1a22788c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lembaga-alamat&quot;)</value>
      <webElementGuid>83bb1775-b349-478f-b479-ec7af4b9d17d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='lembaga-alamat']</value>
      <webElementGuid>a1e90b3a-2d09-43d6-ae92-61c5fc4c1dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div/div[10]/div[2]/div/textarea</value>
      <webElementGuid>ca2a4853-39d7-4906-a0bf-5bb51b07793f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4874895a-485a-494e-bd2d-7384f32a97dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'lembaga-alamat' and @name = 'Lembaga[alamat]']</value>
      <webElementGuid>9b6113d2-2515-4ede-af11-a1fd3668b843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
