<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat Lengkap_Lembagaalamat</name>
   <tag></tag>
   <elementGuidId>d6cf5c06-9bc3-46cc-9817-1ec8fe7742e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='lembaga-alamat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lembaga-alamat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>98b47bcb-4308-45b0-8f84-a6f56e079070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lembaga-alamat</value>
      <webElementGuid>c438f1de-df18-427c-8674-33776112c1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>df151f15-2b64-4795-839a-910f310ebf0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Lembaga[alamat]</value>
      <webElementGuid>c3dc1a9c-dd93-45ce-82ab-241faeb1d6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>677cb31f-61bb-4af2-ab9c-1ac5f3214e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lembaga-alamat&quot;)</value>
      <webElementGuid>e83c0510-2f7d-4afb-ad73-5eac391c265c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='lembaga-alamat']</value>
      <webElementGuid>c4961260-cab4-4bfc-b235-615d37cb8766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div/div[10]/div[2]/div/textarea</value>
      <webElementGuid>3273e0be-7d66-4a30-8734-dc6287ffd817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4a9bb759-1afd-4f13-b7ec-0979d7a6a40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'lembaga-alamat' and @name = 'Lembaga[alamat]']</value>
      <webElementGuid>6df914a0-d5b5-4924-85b1-bc9c6ed92e23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
