<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KODE WILAYAH.xlsx</name>
   <tag></tag>
   <elementGuidId>62d4ec5d-063c-4c41-bff9-7af928c587ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='w0']/div/div/div/div[2]/p[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac19088b-f3e3-4dc4-a4fd-7e3272a38b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/backend/web/template/kode-wilayah.xlsx</value>
      <webElementGuid>880186a6-1485-4f59-8860-f879758b8bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>download</name>
      <type>Main</type>
      <value>kode-wilayah.xlsx</value>
      <webElementGuid>b29670b5-6bd0-441e-b9de-86f39de2095b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KODE WILAYAH.xlsx</value>
      <webElementGuid>e3a5e498-3076-41af-b717-a608101b937e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w0&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]/p[2]/a[2]</value>
      <webElementGuid>77dfd799-5eec-4823-8f37-915946d7565d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div[2]/p[2]/a[2]</value>
      <webElementGuid>ab1636b5-4670-4476-8570-df25b27f5656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KODE WILAYAH.xlsx')]</value>
      <webElementGuid>4dd394da-4103-4c72-9aac-45be97d80908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEMPLATE IMPORT MUSTAHIK.xlsx'])[1]/following::a[1]</value>
      <webElementGuid>ab0b49cf-f1df-4989-ad9d-28aa5503771d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview Data'])[1]/following::a[2]</value>
      <webElementGuid>8ee98a46-cf9b-46e3-9e24-b53a9693205b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PeTIK Jombang'])[1]/preceding::a[1]</value>
      <webElementGuid>7e3f8f1f-1ae1-49ee-9631-706af4ff53e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KODE WILAYAH.xlsx']/parent::*</value>
      <webElementGuid>a123ae2b-4b3f-489f-a027-2c49e6b5b282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/backend/web/template/kode-wilayah.xlsx')]</value>
      <webElementGuid>cc7950d1-ce9b-4032-95a1-40038355dbba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>05bbc4f7-d1a5-4a02-9392-d369091407c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/backend/web/template/kode-wilayah.xlsx' and (text() = 'KODE WILAYAH.xlsx' or . = 'KODE WILAYAH.xlsx')]</value>
      <webElementGuid>b6b2950f-e2b2-462e-ac8b-c3991db1162a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
